        elmat10 = (ammu**2*dmu*
     &    (-(ame**2*ammu**2*kp3**2*2D0) +
     &      kp4*(ame**2*p3p4**2*2D0 +
     &         kp4*(ame**2*kp4 + ammu**2*p1p2 +
     &            kp2*(p1p3 + p1p4) + p1p4*p2p3 + p1p3*p2p4 +
     &            ame**2*ammu**2*2D0) +
     &         kp1*((p2p3 + p2p4)*(kp4 + p3p4) -
     &            ammu**2*kp2*2D0) +
     &         p3p4*(kp2*(p1p3 + p1p4) + ammu**2*p1p2*2D0 +
     &            2D0*(p1p4*p2p3 + p1p3*p2p4 +
     &               ame**2*ammu**2*2D0) +
     &            kp4*(p1p2 + ame**2*4D0))) -
     &      kp3*1D0*(-(ame**2*kp4**2*1D0) +
     &         ammu**2*2D0*
     &          (ammu**2*p1p2 + (kp1 + p1p4)*p2p3 +
     &            p1p3*(kp2 + p2p4) +
     &            ame**2*(p3p4 + ammu**2*2D0)) +
     &         kp4*(ammu**2*p1p2*2D0 + p1p4*p2p4*2D0 +
     &            ame**2*(-(p3p4*1D0) + ammu**2*5D0)))))/
     &  (kp3*kp4**3*(ame**2 + p1p2)**2)
