        elmat4 = -((A0ap*1.25D-1*(kp3**2*
     &          (ampi**2*(ame**2 + p1p2) - kp2*p1p4*2D0 -
     &            p2p4*(ame**2 + p1p2 + p1p4 - p1p3*1D0)*
     &             2D0 - ame**2*kp4*4D0) +
     &         kp4*(ampi**2*kp4*(ame**2 + p1p2) +
     &            ampi**2*kp2*p1p3 + p2p3*p3p4*x12 -
     &            ampi**2*kp2*p1p4*1D0 -
     &            ame**2*ampi**2*p2p3*2D0 -
     &            ampi**2*p1p2*p2p3*2D0 + kp2*p1p3*p2p3*2D0 -
     &            p1p4*p2p3**2*2D0 - p1p3*p2p3*p2p4*2D0 +
     &            kp1*(-(ampi**2*p2p4*1D0) +
     &               ampi**2*kp2*2D0 +
     &               p2p3*(ampi**2 + p2p3*2D0)) +
     &            p1p3*p2p3**2*4D0) +
     &         kp3*(-(ampi**2*kp1*p2p3*1D0) -
     &            kp4*2D0*
     &             ((ame**2 + p1p2)*p3p4 -
     &               p2p3*1D0*(ame**2 + p1p4 - p1p2*1D0) +
     &               p1p3*(p2p3 + ame**2*2D0)) +
     &            p2p4*(kp1*
     &                (-(ampi**2*1D0) + p2p3*2D0 + p3p4*2D0)
     &                + 2D0*
     &                (p1p4*p2p3 +
     &                  ame**2*(ampi**2 - p3p4*1D0) +
     &                  p1p2*(ampi**2 - p3p4*1D0) +
     &                  p1p3*(p2p4 - p2p3*2D0))) +
     &            kp2*(ampi**2*p1p4 + kp1*p3p4*2D0 +
     &               p1p3*
     &                (ampi**2 + p2p4*2D0 - p3p4*2D0 -
     &                  kp4*6D0)))))/
     &     (ampi**2*kp2*kp3*kp4*(ame**2 + p1p2)*
     &       (ampi**2 + p3p4))) +
     &  (B0ap0p*5.D-1*(kp3**2*
     &        (ampi**2*(ame**2 + p1p2) - kp2*p1p4*2D0 -
     &          p2p4*(ame**2 + p1p2 + p1p4 - p1p3*1D0)*2D0 -
     &          ame**2*kp4*4D0) +
     &       kp4*(ampi**2*kp4*(ame**2 + p1p2) +
     &          ampi**2*kp2*p1p3 + p2p3*p3p4*x12 -
     &          ampi**2*kp2*p1p4*1D0 -
     &          ame**2*ampi**2*p2p3*2D0 -
     &          ampi**2*p1p2*p2p3*2D0 + kp2*p1p3*p2p3*2D0 -
     &          p1p4*p2p3**2*2D0 - p1p3*p2p3*p2p4*2D0 +
     &          kp1*(-(ampi**2*p2p4*1D0) + ampi**2*kp2*2D0 +
     &             p2p3*(ampi**2 + p2p3*2D0)) +
     &          p1p3*p2p3**2*4D0) +
     &       kp3*(-(ampi**2*kp1*p2p3*1D0) -
     &          kp4*2D0*((ame**2 + p1p2)*p3p4 -
     &             p2p3*1D0*(ame**2 + p1p4 - p1p2*1D0) +
     &             p1p3*(p2p3 + ame**2*2D0)) +
     &          p2p4*(kp1*
     &              (-(ampi**2*1D0) + p2p3*2D0 + p3p4*2D0) +
     &             2D0*(p1p4*p2p3 +
     &                ame**2*(ampi**2 - p3p4*1D0) +
     &                p1p2*(ampi**2 - p3p4*1D0) +
     &                p1p3*(p2p4 - p2p3*2D0))) +
     &          kp2*(ampi**2*p1p4 + kp1*p3p4*2D0 +
     &             p1p3*(ampi**2 + p2p4*2D0 - p3p4*2D0 -
     &                kp4*6D0)))))/
     &   (kp2*kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4))

