        elmat9 = -(((A0ae + ame2*(-1D0 + B0ae0e*2D0))*
     &      (-(ammu2*kp1**3*1D0) +
     &        ame2*kp2*2D0*
     &         (ammu2*(p1p2 - kp2*1D0) +
     &           p2p4*(p1p3 - kp3*1D0) +
     &           p2p3*(p1p4 - kp4*1D0) +
     &           ame2*(p3p4 + ammu2*2D0)) +
     &        kp1**2*(-(ammu2*kp2*1D0) -
     &           kp4*(p1p3 + p2p3)*1D0 +
     &           p2p4*(p1p3 - kp3*1D0) +
     &           p1p4*(p2p3 - kp3*1D0) +
     &           ame2*(p3p4 + ammu2*2D0) +
     &           p1p2*(p3p4 + ammu2*4D0)) +
     &        kp1*(kp3*(p1p2*(p1p4 + p2p4) +
     &              ame2*kp4*2D0) +
     &           p1p2*(kp4*(p1p3 + p2p3) - ammu2*p1p2*2D0 -
     &              2D0*(p1p4*p2p3 + p1p3*p2p4 +
     &                 ame2*(p3p4 + ammu2*2D0))) +
     &           kp2*(ammu2*p1p2 - p1p3*p1p4*2D0 -
     &              ame2*1D0*(p3p4*2D0 + ammu2*5D0)))))/
     &    (kp1**3*kp2*(ammu2 + p3p4)**2))

