        elmat1 = -((ame**2*C0aex12ee00*2D0*
     &       (kp1**2*(ampi**2 - p3p4*1D0) +
     &         kp2*(kp4*(p2p3 - p1p3*1D0) +
     &            kp2*(ampi**2 - p3p4*1D0) +
     &            p1p3*(p1p4 + p2p3 - p1p3*1D0 - p2p4*1D0)*
     &             2D0 +
     &            kp3*(p2p4 - p1p4*1D0 + p1p3*2D0 - p2p3*2D0))
     &           + kp1*(kp4*(p1p3 - p2p3*1D0) +
     &            kp2*(p3p4 - ampi**2*1D0)*2D0 +
     &            p2p3*(p1p3 + p2p4 - p1p4*1D0 - p2p3*1D0)*
     &             2D0 +
     &            kp3*(p1p4 - p2p4*1D0 - p1p3*2D0 + p2p3*2D0))
     &         ))/(kp1*kp2*kp3*(ampi**2 + p3p4))) -
     &  (ame**2*C1aex12ee00*2D0*
     &     (kp1**2*(ampi**2 - p3p4*1D0) +
     &       kp2*(kp4*(p2p3 - p1p3*1D0) +
     &          kp2*(ampi**2 - p3p4*1D0) +
     &          p1p3*(p1p4 + p2p3 - p1p3*1D0 - p2p4*1D0)*
     &           2D0 + kp3*
     &           (p2p4 - p1p4*1D0 + p1p3*2D0 - p2p3*2D0)) +
     &       kp1*(kp4*(p1p3 - p2p3*1D0) +
     &          kp2*(p3p4 - ampi**2*1D0)*2D0 +
     &          p2p3*(p1p3 + p2p4 - p1p4*1D0 - p2p3*1D0)*
     &           2D0 + kp3*
     &           (p1p4 - p2p4*1D0 - p1p3*2D0 + p2p3*2D0))))/
     &   (kp1*kp2*kp3*(ampi**2 + p3p4))
