        elmat3 = -((ame**2*C1aex34x15e00*
     &       (kp1**2*(p2p4 - p2p3*1D0) +
     &         ame**2*kp2*
     &          (kp4 + p1p3 + p2p4 - kp3*1D0 - p1p4*1D0 -
     &            p2p3*1D0) +
     &         kp1*(ame**2*(kp3 - kp4*1D0) +
     &            kp2*(p1p3 - p1p4*1D0) +
     &            p1p2*(p1p4 + p2p3 - p1p3*1D0 - p2p4*1D0)))*
     &       2D0)/(kp1**2*kp2*(ampi**2 + p3p4))) -
     &  (C2aex34x15e00*2D0*
     &     (ame**4*kp2*(kp4 + p1p3 + p2p4 - kp3*1D0 -
     &          p1p4*1D0 - p2p3*1D0) +
     &       kp1**3*(p2p3 - p2p4*1D0) +
     &       kp1**2*(ame**2*p1p4 + kp2*p1p4 + kp2*p2p3 -
     &          ame**2*p1p3*1D0 - kp2*p1p3*1D0 -
     &          kp2*p2p4*1D0 + kp4*(p1p2 + ame**2*2D0) -
     &          kp3*1D0*(p1p2 + ame**2*2D0)) +
     &       kp1*(kp2**2*p1p4 + ame**2*p1p2*p1p4 +
     &          ame**2*kp2*p2p3 + ame**2*p1p2*p2p3 -
     &          kp2**2*p1p3*1D0 - ame**2*p1p2*p1p3*1D0 -
     &          ame**2*(kp2 + p1p2)*p2p4*1D0 +
     &          kp3*(ame**4 + kp2*(p1p2 + ame**2*2D0)) -
     &          kp4*1D0*(ame**4 + kp2*(p1p2 + ame**2*2D0)))))/
     &   (kp1**2*kp2*(ampi**2 + p3p4)) -
     &  (ame**2*C0aex34x15e00*
     &     (kp1**2*(p2p4 - p2p3*1D0) +
     &       ame**2*kp2*(kp4 + p1p3 + p2p4 - kp3*1D0 -
     &          p1p4*1D0 - p2p3*1D0) +
     &       kp1*(ame**2*(kp3 - kp4*1D0) +
     &          kp2*(p1p3 - p1p4*1D0) +
     &          p1p2*(p1p4 + p2p3 - p1p3*1D0 - p2p4*1D0)))*4D0
     &     )/(kp1**2*kp2*(ampi**2 + p3p4))
