        elmat1 = (E0L*p1p3*(kp1**2*
     &       (p1p4*p2p3 + p1p3*p2p4 + amme**2*p3p4 +
     &         amme**2*mmu**2*2D0 + mmu**2*p1p2*2D0) +
     &      amme**2*kp2*(-(mmu**2*kp2*1D0) - kp4*p2p3*1D0 -
     &         kp3*p2p4*1D0 + mmu**2*p1p2*2D0 +
     &         p1p4*p2p3*2D0 + p1p3*p2p4*2D0 +
     &         amme**2*p3p4*2D0 + amme**2*mmu**2*4D0) -
     &      kp1*1D0*(kp2*
     &          (p1p3*p1p4*2D0 + amme**2*(p3p4 + mmu**2*3D0))
     &          + p1p2*(-(kp4*p1p3*1D0) - kp3*p1p4*1D0 +
     &            mmu**2*p1p2*2D0 + p1p4*p2p3*2D0 +
     &            p1p3*p2p4*2D0 + amme**2*p3p4*2D0 +
     &            amme**2*mmu**2*4D0)))*1.6D1)/
     &  (kp1*kp2*(mmu**2 + p3p4))
