        elmat1 = -(((mmu**2*kp1**2*p1ap2b*2D0 -
     &        kp2*1D0*(amme**2*mmu**2*kap1b +
     &           amme**2*mmu**2*p1ap2b + amme**2*kp4*p1ap3b +
     &           amme**2*p1ap4b*p1p3 + amme**2*p1ap3b*p1p4 +
     &           amme**2*p1ap4b*p2p3 + amme**2*kap1b*p3p4 +
     &           amme**2*p1ap2b*p3p4 -
     &           amme**2*p1ap3b*p2p4*1D0 +
     &           mmu**2*kp2*p1ap1b*2D0 -
     &           mmu**2*p1ap1b*p1p2*2D0 -
     &           kp4*p1ap3b*p1p2*2D0 + kp4*p1ap2b*p1p3*2D0 +
     &           p1ap3b*p1p2*p1p4*2D0 -
     &           p1ap2b*p1p3*p1p4*2D0 + kp4*p1ap1b*p2p3*2D0 -
     &           p1ap1b*p1p4*p2p3*2D0 + kap1b*p1p3*p2p4*2D0 -
     &           amme**2*p1ap1b*p3p4*3D0 +
     &           kp3*(p1ap1b*p2p4*2D0 - amme**2*p1ap4b*3D0) -
     &           p1ap1b*p1p3*p2p4*4D0 -
     &           amme**2*mmu**2*p1ap1b*5D0) +
     &        kp1*(amme**2*mmu**2*kap1b +
     &           amme**2*mmu**2*p1ap1b + amme**2*p1ap3b*p1p4 +
     &           amme**2*p1ap4b*p2p3 + amme**2*p1ap3b*p2p4 +
     &           amme**2*kap1b*p3p4 + amme**2*p1ap1b*p3p4 -
     &           amme**2*p1ap4b*p1p3*1D0 -
     &           mmu**2*p1ap2b*p1p2*2D0 -
     &           kp2*p1ap4b*p1p3*2D0 + p1ap4b*p1p2*p2p3*2D0 -
     &           p1ap2b*p1p4*p2p3*2D0 + kp2*p1ap3b*p2p4*2D0 +
     &           kap1b*p1p3*p2p4*2D0 - p1ap1b*p2p3*p2p4*2D0 +
     &           kp3*(amme**2*p1ap4b - p1ap4b*p1p2*2D0 +
     &              p1ap2b*p1p4*2D0 + p1ap1b*p2p4*2D0) -
     &           amme**2*p1ap2b*p3p4*3D0 +
     &           kp4*(p1ap2b*p1p3*2D0 - amme**2*p1ap3b*3D0) -
     &           p1ap2b*p1p3*p2p4*4D0 -
     &           amme**2*mmu**2*p1ap2b*5D0))*8D0)/
     &    (kp1*kp2*(mmu**2 + p3p4)))

