        elmat1 = (p1a*(mmu**2*kp1**2*(p2p3 - p2p4*1D0) +
     &      kp2*(-(amme**2*
     &            (mmu**2*p2p4 + p2p3*(mmu**2 + p3p4))*1D0) +
     &         p1p3**2*p2p4*2D0 +
     &         p1p3*(amme**2*p3p4 + amme**2*mmu**2*2D0 -
     &            mmu**2*kp2*2D0 + mmu**2*p1p2*2D0 -
     &            kp4*p2p3*2D0 + p1p4*p2p3*2D0) +
     &         kp3*(-(p1p3*p2p4*2D0) +
     &            amme**2*(p3p4 + mmu**2*2D0))) +
     &      kp1*(kp4*(amme**2*mmu**2 + p1p3*p2p3) +
     &         mmu**2*p1p2*p2p4 + p1p2*p2p3*p3p4 -
     &         amme**2*mmu**2*p1p3*1D0 - mmu**2*kp2*p1p3*1D0 -
     &         p1p4*p2p3**2*1D0 - kp2*p1p3*p3p4*1D0 -
     &         amme**2*p2p3*p3p4*1D0 -
     &         amme**2*mmu**2*p2p3*2D0 +
     &         kp3*(amme**2*mmu**2 + p1p4*p2p3 + amme**2*p3p4 -
     &            p1p2*(mmu**2 + p3p4)*1D0 + p1p3*p2p4*2D0) -
     &         p1p3*p2p3*p2p4*3D0))*1.6D1)/
     &  (kp1*kp2*(mmu**2 + p3p4))

