        elmat22 = (A0ap*2.5D-1*(-(kp4*(ame**2 + p1p2)*p3p4**2*1D0) +
     &       p3p4*(kp3*(ame**2 + p1p2)*(ampi**2 - kp4*1D0) +
     &          kp4*(ame**2*ampi**2 + kp1*kp2 +
     &             ampi**2*p1p2 -
     &             1D0*(p1p3 - p1p4*1D0)*(p2p3 - p2p4*1D0)))
     &        + kp3*(ame**2*kp4**2 + kp4**2*p1p2 +
     &          ampi**2*kp3*(ame**2 + p1p2) + kp4*p1p4*p2p3 -
     &          kp2*kp4*p1p4*1D0 - ampi**2*p1p4*p2p3*1D0 -
     &          ampi**2*1D0*
     &           (ame**2*ampi**2 + ampi**2*p1p2 -
     &             p1p3*p2p3*1D0 + kp2*(p1p3 - p1p4*1D0)) +
     &          kp1*(p2p4*(ampi**2 - kp4*1D0) +
     &             ampi**2*(kp2 - p2p3*1D0)) +
     &          p2p4*(p1p3*(kp4 - ampi**2*1D0) +
     &             p1p4*(ampi**2 - kp4*2D0)))))/
     &   (kp3*kp4**3*(ame**2 + p1p2)**2) -
     &  (B0ax450p*(ampi**2 + kp4)*1D0*
     &     (-(kp4*(ame**2 + p1p2)*p3p4**2*1D0) +
     &       p3p4*(kp3*(ame**2 + p1p2)*(ampi**2 - kp4*1D0) +
     &          kp4*(ame**2*ampi**2 + kp1*kp2 +
     &             ampi**2*p1p2 -
     &             1D0*(p1p3 - p1p4*1D0)*(p2p3 - p2p4*1D0)))
     &        + kp3*(ame**2*kp4**2 + kp4**2*p1p2 +
     &          ampi**2*kp3*(ame**2 + p1p2) + kp4*p1p4*p2p3 -
     &          kp2*kp4*p1p4*1D0 - ampi**2*p1p4*p2p3*1D0 -
     &          ampi**2*1D0*
     &           (ame**2*ampi**2 + ampi**2*p1p2 -
     &             p1p3*p2p3*1D0 + kp2*(p1p3 - p1p4*1D0)) +
     &          kp1*(p2p4*(ampi**2 - kp4*1D0) +
     &             ampi**2*(kp2 - p2p3*1D0)) +
     &          p2p4*(p1p3*(kp4 - ampi**2*1D0) +
     &             p1p4*(ampi**2 - kp4*2D0)))))/
     &   (kp3*kp4**3*(ame**2 + p1p2)**2)

