        elmat19 = -((A0ap*2.5D-1*(ampi**2*kp3**2*(ame**2 + p1p2) +
     &         kp4*p3p4*(kp2*p1p3 + p1p4*p2p3 +
     &            (ame**2 + p1p2)*(ampi**2 - p3p4*1D0) +
     &            kp1*(p2p3 + kp2*2D0) +
     &            p2p4*(p1p3 - p1p4*2D0)) +
     &         kp3*(ampi**2*(ame**2 + p1p2)*p3p4 +
     &            kp4**2*x12 +
     &            kp1*(p2p4*(ampi**2 - kp4*1D0)*2D0 +
     &               ampi**2*(-(p2p3*1D0) + kp2*2D0)) -
     &            ampi**2*1D0*
     &             (ame**2*ampi**2 + ampi**2*p1p2 +
     &               p1p3*p2p4 + kp2*(p1p3 - p1p4*2D0) +
     &               p1p4*(p2p3 - p2p4*2D0)) +
     &            kp4*(-((ame**2 + p1p2)*p3p4*1D0) -
     &               p1p4*2D0*(kp2 + p2p4*2D0)))))/
     &     (kp3*kp4**2*(ame**2 + p1p2)**2*x45)) +
     &  (B0ax450p*5.D-1*(ampi**2*kp3**2*(ame**2 + p1p2) +
     &       kp4*p3p4*(kp2*p1p3 + p1p4*p2p3 +
     &          (ame**2 + p1p2)*(ampi**2 - p3p4*1D0) +
     &          kp1*(p2p3 + kp2*2D0) + p2p4*(p1p3 - p1p4*2D0))
     &         + kp3*(ampi**2*(ame**2 + p1p2)*p3p4 +
     &          kp4**2*x12 +
     &          kp1*(p2p4*(ampi**2 - kp4*1D0)*2D0 +
     &             ampi**2*(-(p2p3*1D0) + kp2*2D0)) -
     &          ampi**2*1D0*
     &           (ame**2*ampi**2 + ampi**2*p1p2 + p1p3*p2p4 +
     &             kp2*(p1p3 - p1p4*2D0) +
     &             p1p4*(p2p3 - p2p4*2D0)) +
     &          kp4*(-((ame**2 + p1p2)*p3p4*1D0) -
     &             p1p4*2D0*(kp2 + p2p4*2D0))))*
     &     (ampi**2*2D0 + kp4*3D0))/
     &   (kp3*kp4**2*(ame**2 + p1p2)**2*x45)
