        elmat12 = -((B0ax450p*1D0*(kp4*
     &         (kp2*p1p3 - p1p3*p2p4*1D0 +
     &           ame**2*(p3p4 - ampi**2*1D0) +
     &           p1p2*(p3p4 - ampi**2*1D0) +
     &           p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &        kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &           p1p2*(p3p4 - ampi**2*1D0) +
     &           p2p4*(kp1 - p1p3*1D0) +
     &           p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &           kp4*2D0*(p1p2 + ame**2*3D0))))/
     &    (kp3*kp4*(ame**2 + p1p2)**2))

