        elmat1 = (ame**2*D1aex34e0x25x15e00e*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) +
     &  (D13aex34e0x25x15e00e*kp1*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) +
     &  (D3aex34e0x25x15e00e*kp1*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) -
     &  (C0a0x25eee0*5.D-1*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) -
     &  (C0apx24e0pe*5.D-1*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) +
     &  (ame**2*D0aex34e0x25x15e00e*5.D-1*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) +
     &  (ame**2*D11aex34e0x25x15e00e*5.D-1*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) +
     &  (D22aex34e0x25x15e00e*x25*5.D-1*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) -
     &  (D23aex34e0x25x15e00e*1D0*(kp3 + kp4 - kp1*1D0)*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) +
     &  (D12aex34e0x25x15e00e*(ame**2 - p1p3*1D0 - p1p4*1D0)*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) +
     &  (D2aex34e0x25x15e00e*(ame**2 - p1p3*1D0 - p1p4*1D0)*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) +
     &  (D00aex34e0x25x15e00e*2D0*
     &     (kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &          ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p3*(kp1 - p1p4*1D0 + p1p3*2D0)) +
     &       kp3*(ame**2*(p3p4 - ampi**2*1D0) +
     &          p1p2*(p3p4 - ampi**2*1D0) +
     &          p2p4*(kp1 - p1p3*1D0) +
     &          p1p4*(kp2 - p2p3*1D0 + p2p4*2D0) +
     &          kp4*2D0*(p1p2 + ame**2*3D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) +
     &  (D0a0x13pex24x25eep0*
     &     (kp3**2*2D0*(ampi**2*(ame**2 + p1p2) + p1p3*p2p4 -
     &          (ame**2 + p1p2)*p3p4*1D0 +
     &          p1p4*(ame**2 + p1p2 - kp2*1D0 - p2p4*1D0) -
     &          ame**2*kp4*2D0) +
     &       kp4*(kp2*p1p3*p1p4 - kp2*p1p3**2*2D0 -
     &          p1p3*p1p4*p2p4*2D0 +
     &          ame**2*ampi**2*p1p3*3D0 +
     &          ampi**2*kp2*p1p3*3D0 +
     &          ampi**2*p1p2*p1p3*3D0 -
     &          ampi**2*kp2*p1p4*3D0 + p1p3*p1p4*p2p3*3D0 +
     &          p1p3**2*p2p4*3D0 + ampi**2*p1p4*p2p4*3D0 +
     &          kp4*(-(p1p3*1D0*(ame**2 + p2p3 - p2p4*1D0)) +
     &             ame**2*ampi**2*3D0 +
     &             p1p2*(-(p1p3*1D0) + ampi**2*3D0)) -
     &          ame**2*ampi**4*4D0 - ampi**4*p1p2*4D0 -
     &          p1p3**2*p2p3*4D0 - ampi**2*p1p4*p2p3*4D0 -
     &          ampi**2*p1p3*p2p4*4D0 +
     &          p3p4*(p1p3*(kp2 - (ame**2 + p1p2)*3D0) +
     &             ampi**2*(ame**2 + p1p2)*4D0) +
     &          kp1*(p2p4*(p1p3 - p3p4*1D0 - ampi**2*2D0) +
     &             kp2*(p3p4 + ampi**2*2D0) +
     &             p2p3*(-(kp4*1D0) - p1p3*2D0 + ampi**2*4D0))
     &            + ampi**2*p1p3*p2p3*5D0) -
     &       kp3*1D0*(ame**2*ampi**4 + ampi**4*p1p2 +
     &          ampi**2*p1p4*p2p3 + ampi**2*p1p3*p2p4 -
     &          kp2*p1p4**2*1D0 - ampi**2*p1p3*p2p3*1D0 -
     &          ampi**2*p1p4*p2p4*1D0 + ame**2*kp4**2*2D0 -
     &          ampi**2*kp2*p1p4*2D0 + kp2*p1p3*p1p4*2D0 -
     &          p1p4**2*p2p4*2D0 + ame**2*ampi**2*p1p4*3D0 +
     &          ampi**2*p1p2*p1p4*3D0 + p1p4**2*p2p3*3D0 +
     &          p1p3*p1p4*p2p4*3D0 +
     &          (ame**2 + p1p2)*p3p4**2*3D0 +
     &          kp1*(p2p3*(ampi**2 + p1p4 - p3p4*1D0)*2D0 -
     &             kp2*1D0*(ampi**2 + p3p4*2D0) +
     &             p2p4*(-(p1p4*1D0) - p3p4*1D0 + kp4*3D0)) -
     &          p1p3*p1p4*p2p3*4D0 -
     &          p3p4*1D0*
     &           (p1p4*(-(kp2*1D0) - p2p4*2D0 +
     &                (ame**2 + p2p3)*3D0) +
     &             ame**2*ampi**2*4D0 +
     &             p1p2*(p1p4*3D0 + ampi**2*4D0) +
     &             p1p3*(p2p4*3D0 - p2p3*4D0)) +
     &          kp4*(p1p3*2D0*(ame**2 + kp2*3D0) +
     &             p1p2*(p1p4 - p1p3*2D0 - ampi**2*3D0 +
     &                p3p4*4D0) +
     &             p2p3*(-(p1p4*1D0) + p1p3*2D0)*5D0 -
     &             ame**2*1D0*
     &              (p1p4 - p2p4*2D0 - p3p4*2D0 + p2p3*4D0 +
     &                ampi**2*5D0) + p2p4*(p1p4 - p1p3*6D0))))
     &     )/(kp3*kp4*(ame**2 + p1p2)) +
     &  (D1apx250x24x13ep0ee*
     &     (ampi**2*kp3**2*(ame**2 + p1p2) +
     &       kp4*(ame**2*ampi**4 + ampi**2*kp2*p1p3 +
     &          ampi**2*p1p3*p2p3 + ampi**2*p1p4*p2p3 +
     &          ampi**2*kp1*p2p4 + ampi**2*p1p3*p2p4 -
     &          ame**2*ampi**2*p1p3*1D0 - kp2*p1p3*p1p4*1D0 -
     &          p1p3*p1p4*p2p3*1D0 - kp1*p1p3*p2p4*1D0 -
     &          p1p3**2*p2p4*1D0 + ampi**2*kp2*p1p4*2D0 +
     &          p1p3*p1p4*p2p4*2D0 +
     &          kp4*(kp1*p2p3 +
     &             p1p3*(ame**2 + p2p3 - p2p4*1D0) -
     &             ame**2*ampi**2*2D0 +
     &             p1p2*(p1p3 - ampi**2*2D0)) -
     &          ampi**2*p1p4*p2p4*3D0 - ame**2*p3p4**2*3D0 +
     &          p1p2*(ampi**2 - p3p4*1D0)*
     &           (ampi**2 - p1p3*1D0 + p3p4*3D0) +
     &          p3p4*(ame**2*ampi**2*2D0 + p1p4*p2p3*3D0 +
     &             kp1*(p2p4 - kp2*1D0 - p2p3*3D0) +
     &             p1p3*(ame**2 + p2p4*3D0 - kp2*4D0 -
     &                p2p3*6D0))) +
     &       kp3*(ame**2*ampi**2*p1p4 + ampi**2*p1p2*p1p4 +
     &          p1p4**2*p2p3 + ampi**2*p1p4*p2p4 +
     &          p1p3*p1p4*p2p4 - ampi**2*kp2*p1p3*1D0 -
     &          kp2*p1p4**2*1D0 - ame**2*ampi**4*2D0 +
     &          ame**2*kp4**2*2D0 - ampi**4*p1p2*2D0 -
     &          ampi**2*p1p4*p2p3*2D0 -
     &          ampi**2*p1p3*p2p4*2D0 - p1p4**2*p2p4*2D0 +
     &          (ame**2 + p1p2)*p3p4*
     &           (-(p1p4*1D0) + ampi**2*2D0) +
     &          ampi**2*p1p3*p2p3*3D0 +
     &          kp1*(-(ampi**2*(kp2 + p2p3)*1D0) +
     &             p2p4*(-(p1p4*1D0) + kp4*3D0)) +
     &          kp4*(p1p4*(p2p3 + p2p4 - ame**2*1D0) +
     &             p2p4*(ame**2 - p1p3*1D0)*2D0 +
     &             p1p2*(ampi**2 + p1p4 - p3p4*2D0) +
     &             ame**2*ampi**2*3D0 - ame**2*p3p4*8D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) -
     &  (D1a0x13pex24x25eep0*1D0*
     &     (kp3**2*(p2p4*(kp1 + p1p4 - ame**2*1D0) +
     &          p1p4*(p1p2 - p2p3*1D0) + ame**2*kp4*2D0) -
     &       kp4*1D0*(ame**2*ampi**2*kp4 + ampi**2*kp4*p1p2 +
     &          ame**2*ampi**2*p1p3 + ame**2*p1p3**2 +
     &          ame**2*ampi**2*p1p4 + ame**2*ampi**2*p2p3 +
     &          kp1**2*p2p3 + ame**2*kp4*p2p3 +
     &          ame**2*p1p3*p2p4 + ampi**2*p1p4*p2p4 -
     &          ame**2*kp4*p1p3*1D0 - ame**2*p1p3*p1p4*1D0 -
     &          ame**2*p1p3*p2p3*1D0 - ame**2*ampi**4*2D0 -
     &          ampi**4*p1p2*2D0 - kp4*p1p2*p1p3*2D0 -
     &          ampi**2*p1p4*p2p3*2D0 -
     &          ame**2*ampi**2*p2p4*2D0 -
     &          ampi**2*p1p3*p2p4*2D0 - p1p3*p1p4*p2p4*2D0 +
     &          kp1*(p2p4*(p1p3 - ampi**2*1D0) +
     &             p1p2*(p3p4 - ampi**2*1D0) +
     &             kp2*(ampi**2 - p1p3*1D0) +
     &             ame**2*(p1p3 + p3p4 - ampi**2*2D0) +
     &             p2p3*(-(p1p3*1D0) - p1p4*1D0 + ampi**2*2D0)
     &             ) + ampi**2*p1p2*p1p3*3D0 +
     &          ampi**2*p1p3*p2p3*3D0 + p1p3*p1p4*p2p3*3D0 +
     &          p1p3**2*p2p4*3D0 +
     &          kp2*(-(ampi**2*p1p4*1D0) +
     &             ame**2*(-(p3p4*1D0) + ampi**2*2D0) +
     &             p1p3*(-(ame**2*1D0) + ampi**2*2D0 +
     &                p1p4*2D0) - p1p3**2*3D0) +
     &          p3p4*(ame**2*
     &              (p2p4 + ampi**2*2D0 - p1p3*2D0) +
     &             p1p2*(ampi**2*2D0 - p1p3*3D0)) -
     &          p1p3**2*p2p3*4D0) +
     &       kp3*(ame**2*ampi**4 + ame**2*ampi**2*p1p4 +
     &          ame**2*kp2*p1p4 + kp1*kp2*p1p4 +
     &          ame**2*p1p3*p1p4 + kp2*p1p3*p1p4 +
     &          ampi**2*p1p3*p2p3 + ampi**2*p1p4*p2p3 +
     &          p1p4**2*p2p3 + ame**2*ampi**2*p2p4 +
     &          ampi**2*p1p3*p2p4 + ame**2*p1p4*p2p4 +
     &          ame**2*p3p4**2 - ame**2*ampi**2*p1p3*1D0 -
     &          ame**2*kp1*p1p4*1D0 - ampi**2*kp2*p1p4*1D0 -
     &          ame**2*p1p4**2*1D0 - ampi**2*kp1*p2p3*1D0 -
     &          ame**2*p1p4*p2p3*1D0 - kp1**2*p2p4*1D0 -
     &          p1p3*p1p4*p2p3*2D0 - ampi**2*kp1*p2p4*2D0 -
     &          p1p3**2*p2p4*2D0 - kp1*p1p4*p2p4*2D0 -
     &          p1p4**2*p2p4*2D0 +
     &          p1p2*(ampi**2 - p3p4*1D0)*
     &           (ampi**2 + kp1 + p1p4 - p3p4*1D0 - p1p3*2D0)
     &           + p3p4*(-(ame**2*kp2*1D0) +
     &             kp1*(ame**2 + p2p3 + p2p4 - kp2*1D0) +
     &             p2p3*(ame**2 - p1p4*1D0) -
     &             ame**2*ampi**2*2D0 -
     &             p2p4*1D0*(p1p3 + ame**2*2D0 - p1p4*2D0)) +
     &          kp1*p1p3*p2p4*3D0 - ampi**2*p1p4*p2p4*3D0 +
     &          p1p3*p1p4*p2p4*5D0 +
     &          kp4*(ame**2*p2p3 + p1p3*p2p3 + p1p3*p2p4 -
     &             ame**2*p2p4*1D0 + ame**4*2D0 -
     &             p1p4*p2p3*2D0 - ame**2*p1p4*3D0 +
     &             p1p2*(-(ame**2*2D0) + p3p4*2D0 -
     &                ampi**2*3D0 + p1p3*3D0) +
     &             kp1*(-((ame**2 + p1p2)*2D0) + p2p3*3D0) +
     &             ame**2*p3p4*4D0 + ame**2*p1p3*6D0 -
     &             ame**2*ampi**2*9D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)) +
     &  (D1a0x24px25x13eeep0*
     &     (kp3**2*(-(ampi**2*(ame**2 + p1p2)*1D0) +
     &          p1p4*(ame**2 + kp2*2D0) +
     &          p2p4*(ame**2 - p1p3*2D0 + p1p4*2D0) +
     &          ame**2*kp4*4D0) +
     &       kp4*(ame**2*ampi**2*p1p3 + ame**2*p1p3**2 +
     &          ame**2*ampi**2*p1p4 + ame**2*ampi**2*p2p3 +
     &          kp1**2*p2p3 + ame**2*kp4*p2p3 +
     &          ame**2*p1p3*p2p4 + kp4*p1p3*p2p4 +
     &          ampi**2*p1p4*p2p4 - kp4*p1p2*p1p3*1D0 -
     &          ame**2*p1p3*p1p4*1D0 - ame**2*p1p3*p2p3*1D0 -
     &          kp4*p1p3*p2p3*1D0 - ame**2*ampi**4*2D0 -
     &          ampi**4*p1p2*2D0 - ampi**2*p1p4*p2p3*2D0 -
     &          ame**2*ampi**2*p2p4*2D0 -
     &          ampi**2*p1p3*p2p4*2D0 - p1p3*p1p4*p2p4*2D0 +
     &          kp1*(ame**2*p1p3 + ampi**2*p2p4 +
     &             p1p2*(p3p4 - ampi**2*1D0) +
     &             p2p3*(ampi**2 - kp4*1D0 - p1p4*1D0) +
     &             p3p4*(ame**2 - p2p4*1D0) -
     &             ame**2*ampi**2*2D0 +
     &             kp2*(p1p3 + p3p4 - ampi**2*2D0)) +
     &          kp2*(p1p3*(p1p4 + p3p4 - ame**2*1D0) -
     &             p1p3**2*2D0 +
     &             ame**2*(-(p3p4*1D0) + ampi**2*2D0)) +
     &          ampi**2*p1p2*p1p3*3D0 +
     &          ampi**2*p1p3*p2p3*3D0 + p1p3*p1p4*p2p3*3D0 +
     &          p1p3**2*p2p4*3D0 +
     &          p3p4*(ame**2*
     &              (p2p4 + ampi**2*2D0 - p1p3*2D0) +
     &             p1p2*(ampi**2*2D0 - p1p3*3D0)) -
     &          p1p3**2*p2p3*4D0) -
     &       kp3*1D0*(ame**2*ampi**4 + ampi**4*p1p2 +
     &          ampi**2*kp2*p1p3 + ame**2*ampi**2*p1p4 +
     &          ame**2*kp2*p1p4 + ampi**2*p1p2*p1p4 +
     &          ame**2*p1p3*p1p4 + ampi**2*p1p3*p2p3 +
     &          ampi**2*p1p4*p2p3 + p1p4**2*p2p3 +
     &          ame**2*ampi**2*p2p4 + ampi**2*p1p3*p2p4 +
     &          ame**2*p1p4*p2p4 + (ame**2 + p1p2)*p3p4**2 -
     &          ame**2*ampi**2*p1p3*1D0 -
     &          ampi**2*kp2*p1p4*1D0 - ame**2*p1p4**2*1D0 -
     &          kp2*p1p4**2*1D0 - ame**2*p1p4*p2p3*1D0 -
     &          kp1**2*p2p4*1D0 + ame**2*kp4**2*2D0 -
     &          ampi**2*p1p2*p1p3*2D0 + kp2*p1p3*p1p4*2D0 -
     &          p1p3*p1p4*p2p3*2D0 - p1p3**2*p2p4*2D0 -
     &          p1p4**2*p2p4*2D0 -
     &          p3p4*1D0*
     &           (p2p3*(p1p4 - ame**2*1D0) +
     &             ame**2*ampi**2*2D0 +
     &             p1p2*(p1p4 + ampi**2*2D0 - p1p3*2D0) +
     &             kp2*(ame**2 - p1p4*1D0 + p1p3*2D0) +
     &             p2p4*(p1p3 + ame**2*2D0 - p1p4*2D0)) -
     &          ampi**2*p1p4*p2p4*3D0 +
     &          kp1*(-(kp2*1D0*(ampi**2 + p1p4 - p3p4*2D0)) +
     &             p1p3*p2p4*3D0 +
     &             p1p4*(p2p3 - ame**2*1D0 - p2p4*3D0) +
     &             ampi**2*(p1p2 - p2p3*1D0 - p2p4*3D0) +
     &             p3p4*(ame**2 - p1p2*1D0 + p2p4*3D0) +
     &             kp4*(-(p1p2*2D0) + p2p4*3D0 - ame**2*4D0))
     &           + p1p3*p1p4*p2p4*5D0 +
     &          kp4*(ame**2*p2p3 + p1p4*p2p4 -
     &             p1p4*p2p3*1D0 - ame**2*p2p4*1D0 +
     &             ame**4*2D0 - ame**2*p1p4*2D0 -
     &             p1p3*p2p3*2D0 + p1p3*p2p4*2D0 +
     &             ame**2*p3p4*2D0 +
     &             kp2*2D0*(ame**2 - p1p3*3D0) +
     &             p1p2*(p1p4 - ame**2*2D0 - ampi**2*3D0 +
     &                p1p3*4D0) + ame**2*p1p3*7D0 -
     &             ame**2*ampi**2*9D0))))/
     &   (kp3*kp4*(ame**2 + p1p2))
