#!/bin/bash

# get basename of file
filename=$(basename "$1")

# make sure the input is equal to the basename, i.e. no absolute path is
# supported
if [ "$filename" != "$1" ]; then
    echo "Demo file $1 must be located in the demos folder!"
    exit
fi

# truncate extension if there is any
filename="${filename%.*}"

# check if demo file exists, add the expected .f90 or .cpp extension
extension_fortran="$filename.f90"
extension_cpp="$filename.cpp"
if [ -f "$extension_fortran" ]; then
    extension=$extension_fortran
elif [ -f "$extension_cpp" ]; then
    extension=$extension_cpp
else
    echo "Demo file $filename not found!"
    exit
fi

# switch to build directory
cd ../build/
if [ $? -ne 0 ]
then
  echo "Failed switching to recola's build dir. Make sure recola is built." >&2
  exit
fi

if [ ! -f "Makefile" ] && [ ! -f "makefile" ] ; then
    echo "WARNING. Did not find a makefile in build. Expecting compilation to fail!"
fi

make $filename
if [ $? -ne 0 ]
then
  echo "Failed to compile $extension. Stopping." >&2
  exit
fi

cd ../demos

time ./$filename

exit


