        elmat10 = -(((A0ae + ame**2*(-1D0 + B0ae0e*2D0))*
     &      (-(ame**2*ammu**2*kp1**2*2D0) +
     &        kp2*(-(ammu**2*kp2**2*1D0) +
     &           kp3*(p1p2*(p1p4 + p2p4) + ame**2*kp4*2D0) +
     &           p1p2*(kp4*(p1p3 + p2p3) - ammu**2*p1p2*2D0 -
     &              2D0*(p1p4*p2p3 + p1p3*p2p4 +
     &                 ame**2*(p3p4 + ammu**2*2D0))) +
     &           kp2*(-(kp4*(p1p3 + p2p3)*1D0) +
     &              p2p4*(p1p3 - kp3*1D0) +
     &              p1p4*(p2p3 - kp3*1D0) +
     &              ame**2*(p3p4 + ammu**2*2D0) +
     &              p1p2*(p3p4 + ammu**2*4D0))) +
     &        kp1*(-(ammu**2*kp2**2*1D0) +
     &           ame**2*2D0*
     &            (ammu**2*p1p2 + p1p4*(p2p3 - kp3*1D0) +
     &              p1p3*(p2p4 - kp4*1D0) +
     &              ame**2*(p3p4 + ammu**2*2D0)) +
     &           kp2*(ammu**2*p1p2 - p2p3*p2p4*2D0 -
     &              ame**2*1D0*(p3p4*2D0 + ammu**2*5D0)))))/
     &    (kp1*kp2**3*(ammu**2 + p3p4)**2))

