        elmat5 = (ame**2*D122aeex340x12x15e0ee*
     &     (p1p3 + p2p3 - p1p4*1D0 - p2p4*1D0)*
     &     (kp1*(kp4*(p1p3 + p2p3) + kp3*(p1p4 + p2p4)) -
     &       kp2*(kp4*(p1p3 + p2p3) + kp3*(p1p4 + p2p4))*
     &        1D0 + (p1p3 + p2p4 - p1p4*1D0 - p2p3*1D0)*
     &        (kp4*(p1p3 + p2p3) - kp3*(p1p4 + p2p4)*1D0))*2D0
     &     )/(kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) -
     &  (D233aeex340x12x15e0ee*(kp3 - kp4*1D0)*2D0*
     &     ((kp3*(p1p4 + p2p4) - kp4*(p1p3 + p2p3)*1D0)*
     &        ((ame**2 + p1p2)*(kp3 - kp4*1D0) +
     &          kp2*(p1p4 - p1p3*1D0)) +
     &       kp1*((p2p3 - p2p4*1D0)*
     &           (kp4*(p1p3 + p2p3) - kp3*(p1p4 + p2p4)*1D0)
     &           + kp2*(kp4*(p1p3 + p2p3) +
     &             kp3*(p1p4 + p2p4))*2D0)))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) -
     &  (D223aeex340x12x15e0ee*
     &     (p1p3 + p2p3 - p1p4*1D0 - p2p4*1D0)*2D0*
     &     ((kp3*(p1p4 + p2p4) - kp4*(p1p3 + p2p3)*1D0)*
     &        ((ame**2 + p1p2)*(kp3 - kp4*1D0) +
     &          kp2*(p1p4 - p1p3*1D0)) +
     &       kp1*((p2p3 - p2p4*1D0)*
     &           (kp4*(p1p3 + p2p3) - kp3*(p1p4 + p2p4)*1D0)
     &           + kp2*(kp4*(p1p3 + p2p3) +
     &             kp3*(p1p4 + p2p4))*2D0)))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) -
     &  (ame**2*D111aeex340x12x15e0ee*(p1p3 - p1p4*1D0)*2D0*
     &     (kp4*p1p3*(kp2 + p1p4 + p2p3 - kp1*1D0 -
     &          p1p3*1D0 - p2p4*1D0) +
     &       kp3*(p1p4*(kp2 + p1p3 + p2p4 - kp1*1D0 -
     &             p1p4*1D0 - p2p3*1D0) +
     &          kp4*(ame**2 - p1p2*1D0)*2D0)))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) -
     &  (D133aeex340x12x15e0ee*(kp3 - kp4*1D0)*2D0*
     &     ((ame**2 + p1p2)*(kp3 - kp4*1D0)*
     &        (kp3*p1p4 - kp4*p1p3*1D0) +
     &       kp2*(kp3*p1p4**2 - (kp3 + kp4)*p1p3*p1p4*1D0 +
     &          kp4*(p1p3**2 - ame**2*kp3*2D0)) +
     &       kp1*(kp4*p1p3*(p2p3 - p2p4*1D0 + kp2*2D0) +
     &          kp3*(ame**2*kp4*2D0 +
     &             p1p4*(p2p4 - p2p3*1D0 + kp2*2D0)))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (C1aex150e0e*(kp4**2*(ame**2 + p1p2)*p1p3 -
     &       kp3*p1p4*1D0*
     &        (kp1*(p2p4 - p2p3*1D0) - ame**2*ampi**2*2D0 -
     &          ampi**2*p1p2*2D0 -
     &          1D0*(p1p3 - p1p4*1D0)*
     &           (kp2 - p2p3*2D0 + p2p4*2D0) +
     &          (ame**2 + p1p2)*(kp3 + p3p4*2D0)) +
     &       kp4*(p1p3**2*(kp2 + p2p3*2D0 - p2p4*2D0) +
     &          kp3*(p1p4*(p1p2 - ame**2*1D0) +
     &             ame**2*(p2p4 - p2p3*1D0)*2D0) +
     &          p1p3*(p3p4*x12 - kp2*p1p4*1D0 +
     &             kp3*(ame**2 - p1p2*1D0) -
     &             ame**2*ampi**2*2D0 - ampi**2*p1p2*2D0 +
     &             (p2p3 - p2p4*1D0)*(kp1 - p1p4*2D0)))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) -
     &  (ame**2*D112aeex340x12x15e0ee*2D0*
     &     (-(kp4*1D0*(kp1 + p1p3 + p2p4 - kp2*1D0 -
     &            p1p4*1D0 - p2p3*1D0)*
     &          (-(p1p4*p2p3*1D0) + p1p3**2*2D0 -
     &            p1p3*1D0*(p2p4 + p1p4*2D0 - p2p3*2D0))) +
     &       kp3*(kp4*(ame**2 - p1p2*1D0)*
     &           (p1p3 + p2p3 - p1p4*1D0 - p2p4*1D0)*2D0 -
     &          1D0*(kp1 + p1p4 + p2p3 - kp2*1D0 - p1p3*1D0 -
     &             p2p4*1D0)*
     &           (p2p4*(p1p3 - p1p4*2D0) +
     &             p1p4*(p2p3 + p1p3*2D0 - p1p4*2D0)))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (C1ax12x340eee*(-(kp4**2*(ame**2 + p1p2)*
     &          (p1p3 + p2p3)*1D0) +
     &       kp3*(p1p4 + p2p4)*
     &        (kp2*(p1p4 - p1p3*1D0) - ame**2*ampi**2*2D0 -
     &          ampi**2*p1p2*2D0 -
     &          1D0*(p2p3 - p2p4*1D0)*
     &           (kp1 - p1p3*2D0 + p1p4*2D0) +
     &          (ame**2 + p1p2)*(kp3 + p3p4*2D0)) +
     &       kp4*(-(kp3*(ame**2 + p1p2)*1D0*
     &             (p1p4 + p2p4 - p2p3*1D0)) -
     &          p1p3**2*1D0*(kp2 + p2p3*2D0 - p2p4*2D0) +
     &          p2p3*(kp2*p1p4 +
     &             ame**2*(ampi**2 - p3p4*1D0)*2D0 +
     &             p1p2*(ampi**2 - p3p4*1D0)*2D0 -
     &             1D0*(p2p3 - p2p4*1D0)*(kp1 - p1p4*2D0)) +
     &          p1p3*(kp1*(p2p4 - p2p3*1D0) +
     &             ame**2*ampi**2*2D0 + ampi**2*p1p2*2D0 +
     &             (p1p4 - p2p3*1D0)*
     &              (kp2 + p2p3*2D0 - p2p4*2D0) +
     &             (ame**2 + p1p2)*(kp3 - p3p4*2D0)))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) -
     &  (D113aeex340x12x15e0ee*2D0*
     &     (kp3**2*(kp4*(ame**4 - ame**2*p1p2*1D0)*2D0 +
     &          p1p4*(ame**2*kp2 + p1p2*p1p3 + ame**2*p2p4 -
     &             ame**2*kp1*1D0 - p1p2*p1p4*1D0 -
     &             ame**2*p2p3*1D0 + ame**2*p1p3*2D0 -
     &             ame**2*p1p4*2D0)) +
     &       kp4*p1p3*(kp2*
     &           (-(ame**2*kp4*1D0) + (p1p3 - p1p4*1D0)**2) +
     &          kp4*(ame**2*(p2p4 - p2p3*1D0) +
     &             p1p3*(p1p2 + ame**2*2D0) -
     &             p1p4*1D0*(p1p2 + ame**2*2D0)) +
     &          kp1*(ame**2*kp4 +
     &             (p1p3 - p1p4*1D0)*
     &              (p2p3 - p2p4*1D0 + kp2*2D0))) -
     &       kp3*1D0*(kp4**2*(ame**4 - ame**2*p1p2*1D0)*2D0 +
     &          p1p4*(p1p3 - p1p4*1D0)*
     &           (kp2*(p1p3 - p1p4*1D0) +
     &             kp1*(p2p3 - p2p4*1D0 - kp2*2D0)) +
     &          kp4*(ame**2*kp1*(p1p4 - p1p3*1D0) +
     &             ame**2*kp2*(p1p3 - p1p4*1D0) +
     &             (p1p3 + p1p4)*
     &              (ame**2*(p2p4 - p2p3*1D0) +
     &                p1p3*(p1p2 + ame**2*2D0) -
     &                p1p4*1D0*(p1p2 + ame**2*2D0))))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (C0aex150e0e*(kp4*p1p3*
     &        (kp2*(p3p4 - ampi**2*1D0) +
     &          kp4*(p2p4 - p2p3*1D0)) +
     &       kp3**2*(p1p4*(p2p4 - p2p3*1D0) +
     &          ame**2*kp4*2D0) +
     &       kp3*(kp4*(p1p3 + p1p4)*(p2p3 - p2p4*1D0) +
     &          kp2*p1p4*(ampi**2 - p3p4*1D0) -
     &          ame**2*kp4**2*2D0) +
     &       kp1*(kp3**2*p2p4 +
     &          kp2*(kp3 - kp4*1D0)*(ampi**2 - p3p4*1D0) -
     &          kp4*1D0*(kp4*p2p3 +
     &             p2p4*(p3p4 - ampi**2*1D0)) +
     &          kp3*(-(kp4*p2p4*3D0) +
     &             p2p3*(p3p4 - ampi**2*1D0 + kp4*3D0)))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D123aeex340x12x15e0ee*2D0*
     &     (kp2*(-(ame**2*kp3**2*(p1p4 + p2p4)*1D0) +
     &          kp3*(ame**2*kp4*
     &              (p1p3 + p2p3 - p1p4*1D0 - p2p4*1D0) +
     &             (p1p3 - p1p4*1D0)*
     &              (p2p4*(p1p3 - p1p4*2D0) +
     &                p1p4*(p2p3 + p1p3*2D0 - p1p4*2D0))) +
     &          kp4*(ame**2*kp4*(p1p3 + p2p3) -
     &             1D0*(p1p3 - p1p4*1D0)*
     &              (-(p1p4*p2p3*1D0) + p1p3**2*2D0 -
     &                p1p3*1D0*(p2p4 + p1p4*2D0 - p2p3*2D0))))
     &         + kp1*(ame**2*kp3**2*(p1p4 + p2p4) -
     &          kp4*1D0*(ame**2*kp4*(p1p3 + p2p3) +
     &             (p2p3 - p2p4*1D0 + kp2*2D0)*
     &              (-(p1p4*p2p3*1D0) + p1p3**2*2D0 -
     &                p1p3*1D0*(p2p4 + p1p4*2D0 - p2p3*2D0)))
     &           + kp3*(ame**2*kp4*
     &              (p1p4 + p2p4 - p1p3*1D0 - p2p3*1D0) -
     &             1D0*(p2p4 - p2p3*1D0 + kp2*2D0)*
     &              (p1p3*(p2p4 + p1p4*2D0) +
     &                p1p4*(p2p3 - p1p4*2D0 - p2p4*2D0)))) -
     &       1D0*(kp3 - kp4*1D0)*
     &        (kp4*(p2p3*
     &              (ame**2*(p2p3 - p2p4*1D0) +
     &                p1p4*(p1p2 + ame**2*2D0)) -
     &             p1p3**2*1D0*(p1p2*2D0 + ame**2*3D0) +
     &             p1p3*(p1p2*p2p4 -
     &                (ame**2 + p1p2)*p2p3*2D0 +
     &                p1p4*(p1p2*2D0 + ame**2*3D0))) +
     &          kp3*(ame**2*p2p4**2 +
     &             p2p4*(-(ame**2*p2p3*1D0) -
     &                (ame**2 + p1p2)*p1p4*2D0 +
     &                p1p3*(p1p2 + ame**2*2D0)) +
     &             p1p4*(p1p2*p2p3 +
     &                (p1p3 - p1p4*1D0)*
     &                 (p1p2*2D0 + ame**2*3D0))))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) -
     &  (D3aeex340x12x15e0ee*2D0*
     &     (kp2*(kp4*p1p3*
     &           (kp2*(p3p4 - ampi**2*1D0) +
     &             kp4*(p2p4 - p2p3*1D0)) +
     &          kp3**2*(p1p4*(p2p4 - p2p3*1D0) +
     &             ame**2*kp4*2D0) +
     &          kp3*(kp4*(p1p3 + p1p4)*(p2p3 - p2p4*1D0) +
     &             kp2*p1p4*(ampi**2 - p3p4*1D0) -
     &             ame**2*kp4**2*2D0)) +
     &       kp1**2*(-(kp3**2*p2p4*1D0) +
     &          kp4*(p2p4*(p3p4 - ampi**2*1D0) +
     &             p2p3*(kp4 + p3p4 - ampi**2*1D0)) +
     &          kp3*(p2p3*(ampi**2 - p3p4*1D0 - kp4*3D0) +
     &             p2p4*(ampi**2 - p3p4*1D0 + kp4*3D0))) +
     &       kp1*((kp3 - kp4*1D0)**2*
     &           (p1p4*p2p3 - p1p3*p2p4*1D0) +
     &          kp2**2*(kp3 - kp4*1D0)*(ampi**2 - p3p4*1D0) +
     &          kp2*(kp3**2*(p1p4 + p2p4) -
     &             kp4*1D0*
     &              (kp4*p2p3 +
     &                p1p3*(kp4 + p3p4 - ampi**2*1D0) -
     &                (p1p4 + p2p4)*1D0*(ampi**2 - p3p4*1D0))
     &              + kp3*
     &              (p2p3*p3p4 - ampi**2*p2p3*1D0 +
     &                kp4*p2p3*3D0 - kp4*p2p4*3D0 +
     &                p1p4*(p3p4 - ampi**2*1D0 - kp4*3D0) +
     &                p1p3*(p3p4 - ampi**2*1D0 + kp4*3D0))))))
     &    /(kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (C1aex15x34e0e*(kp3**2*p2p4*x12 +
     &       kp4*(p2p4*(p1p3*(p2p4 - kp2*1D0) +
     &             ame**2*(ampi**2 - p3p4*1D0) +
     &             p1p2*(ampi**2 - p3p4*1D0)) -
     &          p2p3**2*1D0*(kp1 + p1p3*2D0 - p1p4*3D0) +
     &          p2p3*(-(kp2*1D0*(p1p3 - p1p4*2D0)) +
     &             ame**2*ampi**2*3D0 + ampi**2*p1p2*3D0 +
     &             p2p4*(kp1 + p1p3 - p1p4*3D0) -
     &             (ame**2 + p1p2)*1D0*(kp4*2D0 + p3p4*3D0)))
     &        + kp3*(-(p1p4*p2p3**2*1D0) +
     &          p2p3*(kp2*p1p4 +
     &             ame**2*(p3p4 - ampi**2*1D0) +
     &             p1p2*(p3p4 - ampi**2*1D0) -
     &             p2p4*1D0*(kp1 + p1p4 - p1p3*3D0)) +
     &          p2p4*(kp2*(p1p4 - p1p3*2D0) +
     &             ame**2*(p3p4 - ampi**2*1D0)*3D0 +
     &             p1p2*(p3p4 - ampi**2*1D0)*3D0 +
     &             p2p4*(kp1 + p1p4*2D0 - p1p3*3D0)) +
     &          kp4*(ame**2*p1p3 - ame**2*p1p4*1D0 +
     &             (ame**2 + p1p2)*(p2p3 - p2p4*1D0))*4D0)))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D003aeex340x12x15e0ee*2D0*
     &     (kp1*(-((kp3 + kp4)*1D0*
     &             (p2p4*(kp3 + p3p4 - ampi**2*1D0) +
     &               p2p3*(ampi**2 - kp4*1D0 - p3p4*1D0))) +
     &          kp2*(kp3 - kp4*1D0)*(ampi**2 - p3p4*1D0)*2D0)
     &        + kp4*(-(kp2*1D0*(p1p3 - p1p4*1D0)*
     &             (ampi**2 - p3p4*1D0)) +
     &          kp4*(kp2*p1p3 - p1p3*p2p4*1D0 +
     &             ame**2*(p3p4 - ampi**2*1D0)*2D0 +
     &             p1p2*(p3p4 - ampi**2*1D0)*2D0 +
     &             p2p3*(-(p1p4*1D0) + p1p3*2D0))) +
     &       kp3**2*(p1p3*p2p4 + ame**2*ampi**2*2D0 +
     &          ampi**2*p1p2*2D0 - (ame**2 + p1p2)*p3p4*2D0 +
     &          p1p4*(p2p3 - kp2*1D0 - p2p4*2D0) -
     &          kp4*(p1p2 + ame**2*2D0)*4D0) +
     &       kp3*(-(kp2*1D0*(p1p3 - p1p4*1D0)*
     &             (ampi**2 - p3p4*1D0)) +
     &          kp4*(kp2*(p1p3 - p1p4*1D0) - p1p3*p2p3*2D0 +
     &             p1p4*p2p4*2D0) +
     &          kp4**2*(p1p2 + ame**2*2D0)*4D0)))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D23aeex340x12x15e0ee*2D0*
     &     (-(kp1**2*(kp4*p2p3 + kp3*p2p4)*1D0*
     &          (kp3 - kp4*1D0)) -
     &       kp2**2*(kp4*p1p3 + kp3*p1p4)*(kp3 - kp4*1D0)*
     &        2D0 - 1D0*(kp3 - kp4*1D0)*
     &        (kp3**2*(ame**2 + p1p2)*p1p4 +
     &          kp4*(kp4*(ame**2 + p1p2)*p1p3 -
     &             (p1p3 + p2p3)*1D0*
     &              (-(1D0*(ame**2 - p1p2*1D0)*
     &                   (p2p3 - p2p4*1D0)) +
     &                ame**2*p1p3*2D0 - ame**2*p1p4*2D0)) -
     &          kp3*1D0*(kp4*(ame**2 + p1p2)*(p1p3 + p1p4) +
     &             (p1p4 + p2p4)*
     &              ((ame**2 - p1p2*1D0)*(p2p3 - p2p4*1D0) -
     &                ame**2*p1p3*2D0 + ame**2*p1p4*2D0))) +
     &       kp1*(-(kp4*1D0*
     &             ((p1p3 + p2p3)*(p2p3 - p2p4*1D0)*
     &                (p2p3 - p2p4*1D0 + kp2*2D0) +
     &               kp4*
     &                (ame**2*(ampi**2 - p3p4*1D0) +
     &                  p1p2*(ampi**2 - p3p4*1D0) +
     &                  p2p3*(p1p4 + ame**2*2D0 - kp2*2D0) +
     &                  p1p3*
     &                   ((ame**2 + p2p4)*2D0 - kp2*3D0 -
     &                     p2p3*3D0)))) +
     &          kp3**2*(ampi**2*(ame**2 + p1p2) -
     &             (ame**2 + p1p2)*p3p4*1D0 +
     &             p2p4*(p1p3 + ame**2*2D0 - kp2*2D0) +
     &             p1p4*((ame**2 + p2p3)*2D0 - kp2*3D0 -
     &                p2p4*3D0) - kp4*2D0*(p1p2 + ame**2*4D0))
     &            + kp3*((p1p4 + p2p4)*(p2p3 - p2p4*1D0)*
     &              (p2p3 - p2p4*1D0 - kp2*2D0) +
     &             kp4*((ame**2 - kp2*1D0)*(p2p3 - p2p4*1D0)*
     &                 2D0 +
     &                p1p3*
     &                 (p2p4 + ame**2*2D0 - kp2*3D0 -
     &                   p2p3*3D0) -
     &                p1p4*1D0*
     &                 (p2p3 + ame**2*2D0 - kp2*3D0 -
     &                   p2p4*3D0)) +
     &             kp4**2*2D0*(p1p2 + ame**2*4D0))) +
     &       kp2*(kp4*(-((p1p3 + p2p3)*1D0*(p1p3 - p1p4*1D0)*
     &                (p2p3 - p2p4*1D0)) +
     &             kp4*(p1p3**2 +
     &                ame**2*(p3p4 - ampi**2*1D0)*2D0 +
     &                p1p2*(p3p4 - ampi**2*1D0)*2D0 +
     &                p2p3*(ame**2 - p1p4*1D0)*2D0 +
     &                p1p3*
     &                 (-(p1p4*1D0) + ame**2*2D0 - p2p4*2D0 +
     &                   p2p3*4D0))) +
     &          kp3**2*(ampi**2*x12 - p1p4**2*1D0 -
     &             (ame**2 + p1p2)*p3p4*2D0 +
     &             p2p4*(p1p3 - ame**2*1D0)*2D0 +
     &             p1p4*(p1p3 - ame**2*2D0 + p2p3*2D0 -
     &                p2p4*4D0) -
     &             kp4*2D0*(p1p2*2D0 + ame**2*5D0)) +
     &          kp3*((p1p4 + p2p4)*(p1p3 - p1p4*1D0)*
     &              (p2p3 - p2p4*1D0) +
     &             kp4*(p1p4**2 - p1p3**2*1D0 +
     &                ame**2*(p2p4 - p2p3*1D0)*2D0 -
     &                p1p3*2D0*(ame**2 + p2p3*2D0) +
     &                p1p4*2D0*(ame**2 + p2p4*2D0)) +
     &             kp4**2*2D0*(p1p2*2D0 + ame**2*5D0)))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D002aeex340x12x15e0ee*2D0*
     &     (kp3**2*(ame**2 + p1p2)*(p1p4 + p2p4) +
     &       kp3*(ame**2*ampi**2*p2p3 + ampi**2*p1p2*p2p3 +
     &          kp4*p1p2*p2p4 + p1p3**2*p2p4 -
     &          kp4*p1p2*p2p3*1D0 - kp1*p2p3*p2p4*2D0 +
     &          kp1*p2p4**2*2D0 - ame**2*ampi**2*p2p4*3D0 -
     &          ampi**2*p1p2*p2p4*3D0 -
     &          (ame**2 + p1p2)*p3p4*1D0*(p2p3 - p2p4*3D0) +
     &          p1p4**2*(kp2*2D0 - p2p3*3D0 + p2p4*4D0) -
     &          ame**2*kp4*p2p3*5D0 + ame**2*kp4*p2p4*5D0 +
     &          p1p3*(ame**2*ampi**2 + ampi**2*p1p2 -
     &             (ame**2 + p1p2)*p3p4*1D0 - kp2*p1p4*2D0 +
     &             p1p4*p2p3*3D0 - p2p4**2*3D0 -
     &             kp4*1D0*(p1p2 + ame**2*5D0) -
     &             p2p4*1D0*(kp1 + kp2 - p2p3*3D0 + p1p4*5D0))
     &            + p1p4*
     &           (-(p2p3*1D0*(kp1 + kp2 - p2p3*1D0)) -
     &             ame**2*ampi**2*3D0 - ampi**2*p1p2*3D0 +
     &             (ame**2 + p1p2)*p3p4*3D0 + p2p4**2*4D0 +
     &             kp4*(p1p2 + ame**2*5D0) +
     &             p2p4*((kp1 + kp2)*2D0 - p2p3*5D0))) -
     &       kp4*1D0*(ame**2*kp4*p2p3 + kp4*p1p2*p2p3 +
     &          p1p4**2*p2p3 + ame**2*ampi**2*p2p4 +
     &          ampi**2*p1p2*p2p4 + kp1*p2p3**2*2D0 -
     &          kp1*p2p3*p2p4*2D0 - ame**2*ampi**2*p2p3*3D0 -
     &          ampi**2*p1p2*p2p3*3D0 +
     &          (ame**2 + p1p2)*p3p4*
     &           (-(p2p4*1D0) + p2p3*3D0) +
     &          p1p4*(ame**2*(ampi**2 - p3p4*1D0) +
     &             p1p2*(ampi**2 - p3p4*1D0) -
     &             p2p3*1D0*(kp1 + kp2 + p2p3*3D0 - p2p4*3D0))
     &            + p1p3**2*(kp2*2D0 - p2p4*3D0 + p2p3*4D0) +
     &          p1p3*(p2p4**2 -
     &             kp2*1D0*(p2p4 + p1p4*2D0 - p2p3*2D0) -
     &             ame**2*ampi**2*3D0 - ampi**2*p1p2*3D0 +
     &             (ame**2 + p1p2)*(kp4 + p3p4*3D0) +
     &             p2p3*(kp1*2D0 + p2p3*4D0 - p1p4*5D0) -
     &             p2p4*1D0*(kp1 - p1p4*3D0 + p2p3*5D0)))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D0aeex340x12x15e0ee*
     &     (ame**2*kp1**2*(kp3 - kp4*1D0)*
     &        (ampi**2 - p3p4*1D0) -
     &       ame**2*kp2**2*1D0*(kp3 - kp4*1D0)*
     &        (ampi**2 - p3p4*1D0) -
     &       1D0*(kp3 - kp4*1D0)*
     &        (kp4*(-(ame**2*p1p3**2*1D0) +
     &             ame**2*p2p3*(p2p3 - p1p4*1D0 - p2p4*1D0) +
     &             p1p3*(ame**2*p1p4 + p1p2*p2p3*2D0 +
     &                p2p4*(ame**2 - p1p2*2D0))) +
     &          kp3*(ame**2*p2p4**2 -
     &             p2p4*1D0*
     &              (ame**2*(p1p3 + p2p3) - p1p2*p1p4*2D0) +
     &             p1p4*(ame**2*(p1p3 - p1p4*1D0) +
     &                p2p3*(ame**2 - p1p2*2D0)) +
     &             ame**2*kp4*p1p2*4D0)) +
     &       kp2*(-(ame**2*kp3**2*1D0*(p2p4 + p1p4*3D0)) +
     &          kp4*(ame**2*
     &              (p1p4*(p3p4 - ampi**2*1D0) +
     &                p2p4*(p3p4 - ampi**2*1D0) +
     &                p2p3*(ampi**2 + kp4 - p3p4*1D0)) +
     &             p1p3*(ame**2*kp4*3D0 -
     &                1D0*(ampi**2 - p3p4*1D0)*
     &                 (-(p1p2*2D0) + ame**2*3D0))) +
     &          kp3*(ame**2*(p2p3 - p2p4*1D0)*
     &              (ampi**2 - p3p4*1D0 - kp4*3D0) +
     &             ame**2*p1p3*
     &              (ampi**2 - p3p4*1D0 - kp4*5D0) +
     &             p1p4*((ampi**2 - p3p4*1D0)*
     &                 (-(p1p2*2D0) + ame**2*3D0) +
     &                ame**2*kp4*5D0))) +
     &       kp1*(-(kp2*p1p2*(kp3 - kp4*1D0)*
     &             (ampi**2 - p3p4*1D0)*2D0) +
     &          kp3**2*(ame**2*p1p4 +
     &             p2p4*(-(p1p2*2D0) + ame**2*3D0)) -
     &          kp4*1D0*(-(ame**2*ampi**2*p2p4*1D0) +
     &             ame**2*p1p4*(p3p4 - ampi**2*1D0) +
     &             ame**2*p1p3*(ampi**2 + kp4 - p3p4*1D0) -
     &             kp4*p1p2*p2p3*2D0 +
     &             ampi**2*p1p2*p2p4*2D0 -
     &             ame**2*ampi**2*p2p3*3D0 +
     &             ame**2*kp4*p2p3*3D0 +
     &             p3p4*(p2p4*(ame**2 - p1p2*2D0) +
     &                ame**2*p2p3*3D0)) +
     &          kp3*(-(ame**2*ampi**2*p2p3*1D0) +
     &             ampi**2*p1p2*p2p3*2D0 -
     &             ame**2*ampi**2*p2p4*3D0 +
     &             ame**2*p1p4*
     &              (ampi**2 - p3p4*1D0 - kp4*3D0) +
     &             ame**2*p1p3*
     &              (p3p4 - ampi**2*1D0 + kp4*3D0) +
     &             p3p4*(p2p3*(ame**2 - p1p2*2D0) +
     &                ame**2*p2p4*3D0) +
     &             ame**2*kp4*p2p3*5D0 -
     &             ame**2*kp4*p2p4*5D0 - kp4*p1p2*p2p3*6D0 +
     &             kp4*p1p2*p2p4*6D0))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (C0a0x12x34eee*(-(kp3**2*1D0*
     &          ((p1p3 + p1p4)*p2p4 + ame**2*kp4*2D0 -
     &            p1p4*1D0*(kp2 + p2p3*2D0))) +
     &       kp4*(kp4*((p1p3 + p1p4)*p2p3 - p1p3*p2p4*2D0) +
     &          kp2*(p1p4*(ampi**2 - p3p4*1D0) +
     &             p1p3*(-(kp4*1D0) + ampi**2*2D0 - p3p4*2D0))
     &          ) + kp3*(ame**2*kp4**2*2D0 +
     &          kp2*(p3p4 - ampi**2*1D0)*(p1p3 + p1p4*2D0) +
     &          kp4*(kp2*(p1p3 - p1p4*1D0)*3D0 +
     &             p2p4*(p1p4 + p1p3*3D0) -
     &             p2p3*1D0*(p1p3 + p1p4*3D0))) +
     &       kp1*(-(kp2*1D0*(kp3 - kp4*1D0)*
     &             (ampi**2 - p3p4*1D0)) - kp3**2*p2p4*2D0 +
     &          kp4*(p2p4*(p3p4 - ampi**2*1D0)*2D0 +
     &             p2p3*(p3p4 - ampi**2*1D0 + kp4*2D0)) +
     &          kp3*(p2p3*2D0*
     &              (ampi**2 - p3p4*1D0 - kp4*3D0) +
     &             p2p4*(ampi**2 - p3p4*1D0 + kp4*6D0)))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (ame**2*C0aeex12e0e*
     &     (kp3**2*p1p4 + kp3**2*p2p4 - kp4**2*p1p3*1D0 -
     &       kp4**2*p2p3*1D0 +
     &       kp2*(kp3 - kp4*1D0)*(ampi**2 - p3p4*1D0) -
     &       kp1*1D0*(kp3 - kp4*1D0)*(ampi**2 - p3p4*1D0) +
     &       ampi**2*kp4*p1p3*2D0 - ampi**2*kp3*p1p4*2D0 -
     &       ampi**2*kp3*p2p3*2D0 + ampi**2*kp4*p2p4*2D0 +
     &       p3p4*(kp3*(p1p4 + p2p3) - kp4*(p1p3 + p2p4)*1D0)*
     &        2D0 + kp3*kp4*p1p3*3D0 - kp3*kp4*p1p4*3D0 +
     &       kp3*kp4*p2p3*7D0 - kp3*kp4*p2p4*7D0))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (C2aeex12e0e*(ampi**2*kp3*p1p2*p1p3 +
     &       kp4**2*p1p2*p1p3 + ame**2*ampi**2*kp3*p1p4 +
     &       ampi**2*kp3*p1p2*p1p4 + kp4*p1p3*p1p4*p2p3 +
     &       kp3*p1p4**2*p2p3 + ame**2*kp3**2*p2p4 +
     &       kp3*p1p3**2*p2p4 + kp4*p1p3*p1p4*p2p4 -
     &       ame**2*ampi**2*kp4*p1p3*1D0 -
     &       ampi**2*kp4*p1p2*p1p3*1D0 -
     &       kp3**2*p1p2*p1p4*1D0 -
     &       ampi**2*kp4*p1p2*p1p4*1D0 -
     &       ame**2*kp4**2*p2p3*1D0 -
     &       kp3*p1p3*p1p4*p2p3*1D0 - kp4*p1p4**2*p2p3*1D0 -
     &       kp4*p1p3**2*p2p4*1D0 - kp3*p1p3*p1p4*p2p4*1D0 +
     &       kp1*(kp3*(p1p4*p2p3 - p1p3*p2p4*1D0 +
     &             ame**2*(p3p4 - ampi**2*1D0)) +
     &          kp4*(p1p4*p2p3 - p1p3*p2p4*1D0 +
     &             ame**2*(ampi**2 - p3p4*1D0))) +
     &       ame**2*kp4**2*p1p3*2D0 -
     &       ame**2*kp3**2*p1p4*2D0 -
     &       ame**2*ampi**2*kp3*p2p3*2D0 -
     &       ampi**2*kp3*p1p2*p2p3*2D0 +
     &       ampi**2*kp4*p1p2*p2p3*2D0 -
     &       kp4**2*p1p2*p2p3*2D0 - kp3*p1p4*p2p3**2*2D0 +
     &       kp4*p1p4*p2p3**2*2D0 +
     &       ame**2*ampi**2*kp4*p2p4*2D0 -
     &       ampi**2*kp3*p1p2*p2p4*2D0 +
     &       kp3**2*p1p2*p2p4*2D0 +
     &       ampi**2*kp4*p1p2*p2p4*2D0 +
     &       kp3*p1p3*p2p3*p2p4*2D0 -
     &       kp4*p1p3*p2p3*p2p4*2D0 +
     &       kp3*p1p4*p2p3*p2p4*2D0 -
     &       kp4*p1p4*p2p3*p2p4*2D0 - kp3*p1p3*p2p4**2*2D0 +
     &       kp4*p1p3*p2p4**2*2D0 +
     &       kp2*(kp4*(ame**2*(p3p4 - ampi**2*1D0) +
     &             p1p4*p2p3*2D0 - p1p3*p2p4*2D0) +
     &          kp3*(ame**2*(ampi**2 - p3p4*1D0) +
     &             p1p4*p2p3*2D0 - p1p3*p2p4*2D0)) +
     &       ame**2*ampi**2*kp3*p1p3*3D0 -
     &       kp3*kp4*p1p2*p1p3*3D0 -
     &       ame**2*ampi**2*kp4*p1p4*3D0 +
     &       kp3*kp4*p1p2*p1p4*3D0 +
     &       p3p4*(-(kp3*1D0*
     &             (-(p1p2*p2p4*2D0) +
     &               (ame**2 + p1p2)*(p1p4 - p2p3*2D0) +
     &               p1p3*(p1p2 + ame**2*3D0))) +
     &          kp4*((ame**2 + p1p2)*p1p3 - p1p2*p2p3*2D0 -
     &             (ame**2 + p1p2)*p2p4*2D0 +
     &             p1p4*(p1p2 + ame**2*3D0))) +
     &       ame**2*kp3*kp4*p2p3*5D0 -
     &       ame**2*kp3*kp4*p2p4*5D0 +
     &       kp3*kp4*p1p2*p2p3*6D0 - kp3*kp4*p1p2*p2p4*6D0 -
     &       ame**2*kp3*kp4*p1p3*8D0 + ame**2*kp3*kp4*p1p4*8D0
     &       ))/(kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (C2aex15x34e0e*(kp3**2*
     &        (ampi**2*(ame**2 + p1p2) -
     &          (ame**2 + p1p2)*p3p4*1D0 +
     &          p2p4*(p1p3 + x12 - kp1*1D0) +
     &          p1p4*(p2p3 - kp2*1D0 + ame**2*2D0 +
     &             p1p2*2D0 - p2p4*2D0) -
     &          kp4*2D0*(p1p2 + ame**2*3D0)) -
     &       kp4*1D0*(kp1*p1p4*p2p3 + kp1*p2p3**2 -
     &          ame**2*ampi**2*p1p4*1D0 -
     &          ampi**2*p1p2*p1p4*1D0 - p1p4**2*p2p3*1D0 -
     &          ame**2*ampi**2*p2p4*1D0 -
     &          ampi**2*p1p2*p2p4*1D0 - kp1*p2p3*p2p4*1D0 -
     &          kp2*p1p4*p2p3*2D0 +
     &          kp4*(ame**2*ampi**2 - ame**2*p3p4*1D0 +
     &             p2p3*(p1p4 - kp1*1D0 + ame**2*2D0) +
     &             p1p3*(p2p4 - kp2*1D0 + ame**2*2D0 -
     &                p2p3*2D0) +
     &             p1p2*(ampi**2 - p3p4*1D0 + p1p3*2D0 +
     &                p2p3*2D0)) - ame**2*ampi**2*p2p3*3D0 -
     &          ampi**2*p1p2*p2p3*3D0 - p1p4*p2p3**2*3D0 +
     &          p1p4*p2p3*p2p4*3D0 +
     &          (ame**2 + p1p2)*p3p4*
     &           (p1p4 + p2p4 + p2p3*3D0) +
     &          p1p3**2*(kp2 + p2p3*2D0 - p2p4*3D0) +
     &          p1p3*(-(p2p4**2*1D0) +
     &             kp2*(p2p3 + p2p4 - p1p4*1D0) +
     &             p2p3*(kp1 - p1p4*1D0 + p2p3*2D0) +
     &             ame**2*(p3p4 - ampi**2*1D0)*3D0 +
     &             p1p2*(p3p4 - ampi**2*1D0)*3D0 -
     &             p2p4*1D0*(p2p3 + kp1*2D0 - p1p4*3D0))) +
     &       kp3*(kp2*p1p4**2 + kp2*p1p4*p2p3 +
     &          kp1*p1p4*p2p4 + kp2*p1p4*p2p4 + kp1*p2p4**2 -
     &          ame**2*ampi**2*p2p3*1D0 -
     &          ampi**2*p1p2*p2p3*1D0 - p1p4*p2p3**2*1D0 -
     &          p1p3**2*p2p4*1D0 - kp1*p2p3*p2p4*1D0 -
     &          p1p4*p2p3*p2p4*1D0 - kp1*p1p4*p2p3*2D0 +
     &          p1p4**2*p2p4*2D0 + p1p4*p2p4**2*2D0 -
     &          ame**2*ampi**2*p1p4*3D0 -
     &          ampi**2*p1p2*p1p4*3D0 - p1p4**2*p2p3*3D0 -
     &          ame**2*ampi**2*p2p4*3D0 -
     &          ampi**2*p1p2*p2p4*3D0 +
     &          kp4**2*2D0*(p1p2 + ame**2*3D0) +
     &          (ame**2 + p1p2)*p3p4*
     &           (p2p3 + p1p4*3D0 + p2p4*3D0) +
     &          p1p3*(ame**2*(p3p4 - ampi**2*1D0) +
     &             p1p2*(p3p4 - ampi**2*1D0) -
     &             kp2*1D0*(p1p4 + p2p4*2D0) +
     &             p1p4*(-(p2p4*1D0) + p2p3*3D0) +
     &             p2p4*(kp1 + p2p3*3D0 - p2p4*3D0)) +
     &          kp4*(p1p4*
     &              (kp2 + p2p4*2D0 - p1p2*4D0 - ame**2*8D0)
     &              + (p2p3 - p2p4*1D0)*
     &              (-(kp1*1D0) + p1p2*4D0 + ame**2*8D0) +
     &             p1p3*(-(kp2*1D0) - p2p3*2D0 + p1p2*4D0 +
     &                ame**2*8D0)))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D13aeex340x12x15e0ee*
     &     (-(kp1**2*(kp4*p2p3 + kp3*p2p4)*(kp3 - kp4*1D0)*
     &          2D0) + kp2*
     &        (kp3**2*(ame**2*(ampi**2 - p3p4*1D0) -
     &             p1p4**2*2D0 + p1p4*2D0*(p1p3 - ame**2*2D0))
     &            + kp3*2D0*
     &           (p1p4*(p1p4 - p1p3*1D0)*(p2p4 - p2p3*1D0) +
     &             kp4*(p1p4**2 - p1p3**2*1D0 -
     &                ame**2*p1p3*2D0 + ame**2*p1p4*2D0 +
     &                ame**2*(p2p3 - p2p4*1D0)*2D0)) +
     &          kp4*(p1p3*(p1p3 - p1p4*1D0)*(p2p4 - p2p3*1D0)*
     &              2D0 +
     &             kp4*(ame**2*p3p4 - ame**2*ampi**2*1D0 +
     &                p1p3*2D0*(p1p3 - p1p4*1D0 + ame**2*2D0))
     &             )) + kp1*
     &        (kp3*2D0*(p1p4*(p2p3 - p2p4*1D0)*
     &              (p2p3 - p2p4*1D0 - kp2*2D0) +
     &             kp4*(ame**2*(p2p4 - p2p3*1D0)*2D0 +
     &                p1p3*
     &                 (p2p4 + ame**2*2D0 - kp2*3D0 -
     &                   p2p3*3D0) -
     &                p1p4*1D0*
     &                 (p2p3 + ame**2*2D0 - kp2*3D0 -
     &                   p2p4*3D0)) +
     &             kp4**2*2D0*(p1p2 + ame**2*5D0)) +
     &          kp3**2*(p1p3*p2p4*2D0 +
     &             p1p2*(ampi**2 - p3p4*1D0)*2D0 +
     &             ame**2*(ampi**2 - p3p4*1D0)*3D0 -
     &             kp4*4D0*(p1p2 + ame**2*5D0) +
     &             p1p4*((ame**2 + p2p3)*4D0 - kp2*6D0 -
     &                p2p4*6D0)) -
     &          kp4*1D0*(p1p3*(p2p3 - p2p4*1D0)*2D0*
     &              (p2p3 - p2p4*1D0 + kp2*2D0) +
     &             kp4*(p1p4*p2p3*2D0 +
     &                p1p2*(ampi**2 - p3p4*1D0)*2D0 +
     &                ame**2*(ampi**2 - p3p4*1D0)*3D0 +
     &                p1p3*
     &                 ((ame**2 + p2p4)*4D0 - kp2*6D0 -
     &                   p2p3*6D0)))) -
     &       1D0*(kp3 - kp4*1D0)*
     &        (kp3**2*(-(ame**2*p2p4*1D0) +
     &             p1p4*(ame**2 + p1p2*2D0)) +
     &          kp4*(p1p3*2D0*
     &              ((ame**2 - p1p2*1D0)*(p2p3 - p2p4*1D0) -
     &                ame**2*p1p3*2D0 + ame**2*p1p4*2D0) +
     &             kp4*(-(ame**2*p2p3*1D0) +
     &                p1p3*(ame**2 + p1p2*2D0))) +
     &          kp3*(p1p4*2D0*
     &              (-(1D0*(ame**2 - p1p2*1D0)*
     &                   (p2p3 - p2p4*1D0)) +
     &                ame**2*p1p3*2D0 - ame**2*p1p4*2D0) +
     &             kp4*(-(p1p2*2D0*
     &                   (p1p3 + p1p4 + ame**2*4D0)) +
     &                ame**2*
     &                 (p2p3 + p2p4 - p1p3*1D0 - p1p4*1D0 +
     &                   ame**2*8D0))))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D11aeex340x12x15e0ee*
     &     (-(kp3**2*1D0*
     &          (kp1*p1p4*x12 +
     &            kp4*(ame**4 - ame**2*p1p2*1D0)*2D0 +
     &            ame**2*
     &             ((p1p3 - p1p4*1D0)*(p1p4 - p2p4*1D0) +
     &               kp2*p1p4*2D0))) +
     &       kp4*(kp1**2*(p1p4*p2p3 - p1p3*p2p4*1D0)*2D0 +
     &          kp1*(p1p4*
     &              (-(p1p4*p2p3*2D0) +
     &                p1p2*(p3p4 - ampi**2*1D0)*2D0 +
     &                ame**2*(p3p4 - ampi**2*1D0)*3D0) +
     &             p1p3*(kp4*x12 +
     &                p1p2*(p3p4 - ampi**2*1D0)*2D0 +
     &                p1p4*2D0*(p2p3 + p2p4 - ame**2*2D0) +
     &                ame**2*
     &                 (p2p3*2D0 - p2p4*2D0 - ampi**2*3D0 +
     &                   p3p4*3D0)) +
     &             p1p3**2*(-(p2p4*2D0) + ame**2*4D0)) +
     &          ame**2*(-(kp4*1D0*(p1p3 - p1p4*1D0)*
     &                (p1p3 - p2p3*1D0)) +
     &             p1p3*(p1p3 + p2p4 - p1p4*1D0 - p2p3*1D0)*
     &              2D0*(p2p3 - p2p4*1D0 + p1p3*2D0 -
     &                p1p4*2D0) +
     &             kp2*(p1p4*(p3p4 - ampi**2*1D0) -
     &                p1p3**2*4D0 +
     &                p1p3*
     &                 (p3p4 - ampi**2*1D0 + kp4*2D0 -
     &                   p2p3*2D0 + p2p4*2D0 + p1p4*4D0)))) +
     &       kp3*(kp4**2*(ame**4 - ame**2*p1p2*1D0)*2D0 +
     &          kp1**2*(p1p4*p2p3 - p1p3*p2p4*1D0)*2D0 +
     &          kp1*(p1p3**2*p2p4*2D0 +
     &             p1p4*(p1p2*(ampi**2 - p3p4*1D0)*2D0 +
     &                p1p4*2D0*(p2p3 - ame**2*2D0) +
     &                ame**2*
     &                 (p2p3*2D0 - p2p4*2D0 + ampi**2*3D0 -
     &                   p3p4*3D0)) +
     &             p1p3*(p1p2*(ampi**2 - p3p4*1D0)*2D0 +
     &                ame**2*(ampi**2 - p3p4*1D0)*3D0 +
     &                p1p4*
     &                 (-(p2p3*2D0) - p2p4*2D0 + ame**2*4D0)))
     &            + ame**2*
     &           (-(p1p4*(p1p4 + p2p3 - p1p3*1D0 - p2p4*1D0)*
     &                2D0*
     &                (p2p4 - p2p3*1D0 - p1p3*2D0 + p1p4*2D0))
     &               + kp2*
     &              (p1p3*(ampi**2 - p3p4*1D0 - p1p4*4D0) +
     &                p1p4*
     &                 (ampi**2 - p3p4*1D0 - p2p3*2D0 +
     &                   p2p4*2D0 + p1p4*4D0))) +
     &          kp4*(ame**2*p1p3**2 - ame**2*p1p4**2*1D0 -
     &             ame**2*(p2p3 - p2p4*1D0)*2D0*
     &              (ame**2*2D0 - p1p2*2D0 + kp1*3D0) +
     &             p1p4*(kp1*2D0*(p1p2*3D0 + ame**2*7D0) +
     &                ame**2*
     &                 (p2p3 + p2p4 + kp2*4D0 + ame**2*8D0 -
     &                   p1p2*8D0)) -
     &             p1p3*1D0*
     &              (kp1*2D0*(p1p2*3D0 + ame**2*7D0) +
     &                ame**2*
     &                 (p2p3 + p2p4 + kp2*4D0 + ame**2*8D0 -
     &                   p1p2*8D0))))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D001aeex340x12x15e0ee*2D0*
     &     (ampi**2*kp3*p1p2*p1p3 + ame**2*kp3**2*p1p4 +
     &       kp3**2*p1p2*p1p4 + kp3*kp4*p1p2*p1p4 +
     &       ame**2*ampi**2*kp3*p2p4 +
     &       ame**2*ampi**2*kp4*p2p4 + kp3*p1p3**2*p2p4 -
     &       ame**2*kp4**2*p1p3*1D0 - kp3*kp4*p1p2*p1p3*1D0 -
     &       kp4**2*p1p2*p1p3*1D0 -
     &       ampi**2*kp4*p1p2*p1p4*1D0 -
     &       ame**2*ampi**2*kp3*p2p3*1D0 -
     &       ame**2*ampi**2*kp4*p2p3*1D0 -
     &       kp4*p1p4**2*p2p3*1D0 +
     &       ame**2*ampi**2*kp3*p1p3*2D0 -
     &       ame**2*ampi**2*kp4*p1p4*2D0 +
     &       kp2*(kp4*(ame**2*(p3p4 - ampi**2*1D0) +
     &             p1p3*(p1p4 - p1p3*1D0)*2D0) +
     &          kp3*(ame**2*(ampi**2 - p3p4*1D0) +
     &             p1p4*(p1p4 - p1p3*1D0)*2D0)) +
     &       kp1*(kp4*(p1p4*p2p3 +
     &             ame**2*(ampi**2 - p3p4*1D0) +
     &             p1p3*(p2p4 - p2p3*2D0)) -
     &          kp3*1D0*(p1p3*p2p4 +
     &             ame**2*(ampi**2 - p3p4*1D0) +
     &             p1p4*(p2p3 - p2p4*2D0))) +
     &       ampi**2*kp4*p1p2*p1p3*3D0 -
     &       ampi**2*kp3*p1p2*p1p4*3D0 +
     &       kp3*p1p3*p1p4*p2p3*3D0 - kp3*p1p4**2*p2p3*3D0 +
     &       kp4*p1p3**2*p2p4*3D0 - kp4*p1p3*p1p4*p2p4*3D0 +
     &       ame**2*ampi**2*kp4*p1p3*4D0 -
     &       ame**2*ampi**2*kp3*p1p4*4D0 +
     &       ame**2*kp3*kp4*p2p3*4D0 - kp4*p1p3**2*p2p3*4D0 -
     &       ame**2*kp3*kp4*p2p4*4D0 + kp3*p1p4**2*p2p4*4D0 +
     &       p3p4*(kp3*(ame**2*(p2p3 - p2p4*1D0) -
     &             p1p3*1D0*(p1p2 + ame**2*2D0) +
     &             p1p4*(p1p2*3D0 + ame**2*4D0)) +
     &          kp4*(ame**2*(p2p3 - p2p4*1D0) +
     &             p1p4*(p1p2 + ame**2*2D0) -
     &             p1p3*1D0*(p1p2*3D0 + ame**2*4D0))) +
     &       kp4*p1p3*p1p4*p2p3*5D0 -
     &       kp3*p1p3*p1p4*p2p4*5D0 -
     &       ame**2*kp3*kp4*p1p3*9D0 + ame**2*kp3*kp4*p1p4*9D0
     &       ))/(kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D22aeex340x12x15e0ee*2D0*
     &     (-(ame**2*kp3**2*p1p4*p2p3*1D0) -
     &       ame**2*kp4**2*p1p4*p2p3*1D0 -
     &       kp3**2*p1p2*p1p4*p2p3*1D0 -
     &       kp4**2*p1p2*p1p4*p2p3*1D0 +
     &       kp1**2*(kp3 + kp4)*(p1p4*p2p3 - p1p3*p2p4*1D0) +
     &       ame**2*kp4*p1p3**3*2D0 -
     &       ame**2*kp3*p1p3**2*p1p4*2D0 +
     &       ame**2*kp4*p1p3*p1p4**2*2D0 -
     &       ame**2*kp3*p1p4**3*2D0 +
     &       ame**2*kp4*p1p3**2*p2p3*2D0 +
     &       ame**2*kp3*kp4*p1p4*p2p3*2D0 +
     &       kp3*kp4*p1p2*p1p4*p2p3*2D0 +
     &       ame**2*kp4*p1p4**2*p2p3*2D0 -
     &       ame**2*kp4*p1p3*p2p3**2*2D0 +
     &       ame**2*kp3*p1p4*p2p3**2*2D0 -
     &       ame**2*kp4*p2p3**3*2D0 +
     &       ame**2*kp3*p2p4**3*2D0 -
     &       kp2**2*(kp3 + kp4)*(p1p4*p2p3 - p1p3*p2p4*1D0)*
     &        2D0 - ame**2*p2p4**2*2D0*
     &        (kp4*(p1p3 + p2p3) - kp3*1D0*(p1p4 - p2p3*2D0))
     &        - ame**2*kp4*p1p3**2*p1p4*4D0 +
     &       ame**2*kp3*p1p3*p1p4**2*4D0 -
     &       ame**2*kp4*p1p3*p1p4*p2p3*4D0 +
     &       p2p4*(kp3**2*(ame**2 + p1p2)*p1p3 -
     &          kp3*2D0*(kp4*(ame**2 + p1p2)*p1p3 +
     &             ame**2*
     &              (-(p2p3**2*1D0) + (p1p3 - p1p4*1D0)**2 +
     &                p1p4*p2p3*2D0)) +
     &          kp4*(kp4*(ame**2 + p1p2)*p1p3 +
     &             ame**2*p2p3*(p1p3 + p2p3)*4D0)) +
     &       kp2*(-(kp3**2*(ame**2 + p1p2)*(p1p4 + p2p4)*
     &             2D0) +
     &          kp4*((p2p3 + p2p4)*p3p4*x12 -
     &             p1p4**2*p2p3*1D0 - ame**2*p2p3**2*2D0 -
     &             (ame**2 + p1p2)*p2p3*(ampi**2 - kp4*1D0)*
     &              2D0 -
     &             p2p4*(ampi**2*(ame**2 + p1p2) -
     &                ame**2*p2p3*1D0)*2D0 +
     &             p1p4*(p2p3*(ame**2 + p2p4) - p2p3**2*1D0 +
     &                ame**2*(p3p4 - ampi**2*1D0) +
     &                p1p2*(p3p4 - ampi**2*1D0))*2D0 -
     &             p1p3**2*1D0*(p2p4 + ame**2*2D0) +
     &             p1p3*(kp4*x12 -
     &                ampi**2*(ame**2 + p1p2)*2D0 +
     &                p1p4*(p2p3 + p2p4 + ame**2*2D0) +
     &                2D0*
     &                 ((ame**2 + p1p2)*p3p4 +
     &                   p2p4*(ame**2 - p2p4*1D0) +
     &                   p2p3*(p2p4 - ame**2*2D0)))) +
     &          kp3*(p1p3**2*p2p4 +
     &             p1p4**2*(p2p3 + ame**2*2D0) +
     &             p1p4*2D0*
     &              (ampi**2*(ame**2 + p1p2) + p2p3**2 -
     &                p2p3*(ame**2 + p2p4)*1D0 -
     &                (ame**2 + p1p2)*p3p4*1D0 +
     &                ame**2*p2p4*2D0 +
     &                kp4*(p1p2 + ame**2*2D0)*3D0) +
     &             2D0*(p2p3*
     &                 (ampi**2*(ame**2 + p1p2) -
     &                   ame**2*p2p4*1D0 -
     &                   (ame**2 + p1p2)*p3p4*1D0 -
     &                   kp4*(p1p2 + ame**2*2D0)*3D0) +
     &                p2p4*
     &                 (p1p2*(ampi**2 - p3p4*1D0) +
     &                   ame**2*(ampi**2 + p2p4 - p3p4*1D0) +
     &                   kp4*(p1p2 + ame**2*2D0)*3D0)) +
     &             p1p3*(ampi**2*x12 -
     &                (ame**2 + p1p2)*p3p4*2D0 -
     &                p2p4*(ame**2 + p2p3 - p2p4*1D0)*2D0 -
     &                p1p4*1D0*(p2p3 + p2p4 + ame**2*2D0) -
     &                kp4*(p1p2 + ame**2*2D0)*6D0))) +
     &       kp1*(-(kp3**2*(ame**2 + p1p2)*(p1p4 + p2p4)*
     &             1D0) +
     &          kp4*(ame**2*kp4*p2p3 + kp4*p1p2*p2p3 +
     &             (ame**2 + p1p2)*(p2p3 + p2p4)*p3p4 -
     &             ame**2*ampi**2*p2p3*1D0 -
     &             ampi**2*p1p2*p2p3*1D0 - p1p4**2*p2p3*1D0 -
     &             ame**2*ampi**2*p2p4*1D0 -
     &             ampi**2*p1p2*p2p4*1D0 +
     &             ame**2*p2p3**2*2D0 -
     &             ame**2*p2p3*p2p4*2D0 +
     &             p1p3**2*(-(p2p4*1D0) + ame**2*2D0) +
     &             p1p4*(ame**2*p3p4 - ame**2*ampi**2*1D0 +
     &                p1p2*(p3p4 - ampi**2*1D0) -
     &                p2p3*1D0*
     &                 (kp2 + (ame**2 + p2p3 - p2p4*1D0)*2D0))
     &               + p1p3*
     &              (kp4*(ame**2 + p1p2) + kp2*p2p4 +
     &                (ame**2 + p1p2)*p3p4 -
     &                ampi**2*(ame**2 + p1p2)*1D0 -
     &                ame**2*p2p4*2D0 + p2p3*p2p4*2D0 -
     &                p2p4**2*2D0 +
     &                p1p4*(p2p3 + p2p4 - ame**2*2D0) +
     &                ame**2*p2p3*4D0)) +
     &          kp3*(ame**2*ampi**2*p2p3 +
     &             ampi**2*p1p2*p2p3 + ame**2*ampi**2*p2p4 +
     &             ampi**2*p1p2*p2p4 + p1p3**2*p2p4 -
     &             (ame**2 + p1p2)*(p2p3 + p2p4)*p3p4*1D0 +
     &             ame**2*p2p3*p2p4*2D0 -
     &             ame**2*p2p4**2*2D0 +
     &             p1p4**2*(p2p3 - ame**2*2D0) -
     &             kp4*p1p2*p2p3*3D0 + kp4*p1p2*p2p4*3D0 +
     &             p1p3*(ampi**2*(ame**2 + p1p2) -
     &                (ame**2 + p1p2)*p3p4*1D0 +
     &                p1p4*
     &                 (-(p2p3*1D0) - p2p4*1D0 + ame**2*2D0)
     &                 + p2p4*
     &                 (kp2 + (ame**2 + p2p4 - p2p3*1D0)*2D0)
     &                 - kp4*3D0*(p1p2 + ame**2*3D0)) +
     &             p1p4*(ampi**2*(ame**2 + p1p2) -
     &                (ame**2 + p1p2)*p3p4*1D0 +
     &                p2p3**2*2D0 +
     &                p2p3*
     &                 (-(kp2*1D0) + ame**2*2D0 - p2p4*2D0) +
     &                kp4*3D0*(p1p2 + ame**2*3D0) -
     &                ame**2*p2p4*4D0) -
     &             ame**2*kp4*p2p3*9D0 + ame**2*kp4*p2p4*9D0))
     &       ))/(kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) -
     &  (D00aeex340x12x15e0ee*2D0*
     &     (ame**2*ampi**2*kp3*p2p3 +
     &       ame**2*ampi**2*kp4*p2p3 +
     &       ampi**2*kp3*p1p2*p2p4 + ampi**2*kp4*p1p2*p2p4 +
     &       kp4**2*p1p3*p2p4 + kp4*p1p4*p2p3*p2p4 +
     &       kp3*p1p3*p2p4**2 + kp4*p1p3*p2p4**2 -
     &       ampi**2*kp3*p1p2*p2p3*1D0 -
     &       ampi**2*kp4*p1p2*p2p3*1D0 -
     &       kp3**2*p1p4*p2p3*1D0 - kp3*p1p4*p2p3**2*1D0 -
     &       kp4*p1p4*p2p3**2*1D0 -
     &       ame**2*ampi**2*kp3*p2p4*1D0 -
     &       ame**2*ampi**2*kp4*p2p4*1D0 -
     &       kp3*p1p3*p2p3*p2p4*1D0 -
     &       ame**2*ampi**2*kp3**2*2D0 +
     &       ame**2*ampi**2*kp4**2*2D0 -
     &       ampi**2*kp3**2*p1p2*2D0 +
     &       ampi**2*kp4**2*p1p2*2D0 -
     &       ame**2*ampi**2*kp3*p1p3*2D0 -
     &       ame**2*ampi**2*kp4*p1p3*2D0 +
     &       ame**2*ampi**2*kp3*p1p4*2D0 +
     &       ame**2*ampi**2*kp4*p1p4*2D0 +
     &       ame**2*kp3*kp4*p2p3*2D0 +
     &       kp3*kp4*p1p2*p2p3*2D0 - kp3*kp4*p1p4*p2p3*2D0 +
     &       kp4*p1p3*p2p3**2*2D0 - ame**2*kp3*kp4*p2p4*2D0 -
     &       kp3*kp4*p1p2*p2p4*2D0 + kp3*kp4*p1p3*p2p4*2D0 -
     &       kp3*p1p4*p2p4**2*2D0 +
     &       (kp3 + kp4)*p3p4*
     &        (p1p2*p2p3 + kp3*x12 - ame**2*p2p3*1D0 +
     &          p2p4*(ame**2 - p1p2*1D0) -
     &          kp4*(ame**2 + p1p2)*2D0 + ame**2*p1p3*2D0 -
     &          ame**2*p1p4*2D0) +
     &       kp1*(kp3**2*p2p4 +
     &          kp3*(p2p3*
     &              (ampi**2 + p2p4 - kp4*1D0 - p3p4*1D0) +
     &             p2p4*(ampi**2 + kp4 - p2p4*1D0 -
     &                p3p4*1D0) +
     &             ame**2*(ampi**2 - p3p4*1D0)*2D0) +
     &          kp4*(p2p3**2 -
     &             p2p3*1D0*
     &              (ampi**2 + kp4 + p2p4 - p3p4*1D0) -
     &             1D0*(ampi**2 - p3p4*1D0)*
     &              (p2p4 + ame**2*2D0))) +
     &       kp4**2*p1p4*p2p3*3D0 - kp3**2*p1p3*p2p4*3D0 -
     &       kp4*p1p3*p2p3*p2p4*3D0 +
     &       kp3*p1p4*p2p3*p2p4*3D0 + kp3**2*kp4*p1p2*4D0 -
     &       kp3*kp4**2*p1p2*4D0 + ame**2*kp3*kp4*p1p3*4D0 -
     &       ame**2*kp3*kp4*p1p4*4D0 +
     &       kp3*kp4*p1p3*p2p3*4D0 - kp4**2*p1p3*p2p3*4D0 +
     &       kp3**2*p1p4*p2p4*4D0 - kp3*kp4*p1p4*p2p4*4D0 +
     &       kp2*(kp3**2*p1p4*3D0 +
     &          kp4*((ampi**2 - p3p4*1D0)*
     &              (p1p4 + ame**2*2D0) +
     &             p1p3*(ampi**2 + p2p3 - p2p4*1D0 -
     &                p3p4*1D0 - kp4*3D0)) +
     &          kp3*(ame**2*(p3p4 - ampi**2*1D0)*2D0 +
     &             p1p4*(p2p3 + p3p4 - ampi**2*1D0 -
     &                p2p4*1D0 - kp4*5D0) +
     &             p1p3*(p3p4 - ampi**2*1D0 + kp4*5D0))) +
     &       ame**2*kp3**2*kp4*1.2D1 - ame**2*kp3*kp4**2*1.2D1
     &       ))/(kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (C0aex15x34e0e*5.D-1*
     &     (ame**2*kp3*kp4*p1p3 + ame**2*kp4**2*p1p3 +
     &       ame**2*kp3*kp4*p2p3 - ame**2*kp3**2*p1p4*1D0 -
     &       ame**2*kp3*kp4*p1p4*1D0 -
     &       ame**2*kp3*kp4*p2p4*1D0 -
     &       ame**2*ampi**2*kp4*p1p3*2D0 +
     &       kp3*kp4*p1p2*p1p3*2D0 - kp4**2*p1p2*p1p3*2D0 +
     &       ame**2*ampi**2*kp3*p1p4*2D0 +
     &       kp3**2*p1p2*p1p4*2D0 - kp3*kp4*p1p2*p1p4*2D0 +
     &       ame**2*ampi**2*kp3*p2p3*2D0 +
     &       kp3*kp4*p1p3*p2p3*2D0 - kp4**2*p1p3*p2p3*2D0 -
     &       kp3**2*p1p4*p2p3*2D0 + kp3*kp4*p1p4*p2p3*2D0 -
     &       ame**2*ampi**2*kp4*p2p4*2D0 -
     &       kp3*kp4*p1p3*p2p4*2D0 + kp4**2*p1p3*p2p4*2D0 +
     &       kp3**2*p1p4*p2p4*2D0 - kp3*kp4*p1p4*p2p4*2D0 -
     &       ame**2*kp4**2*p2p3*3D0 +
     &       ame**2*kp3**2*p2p4*3D0 +
     &       kp1*(kp3**2*p2p4*2D0 +
     &          kp4*(-(p2p3*(kp4 + p1p3 + p2p3)*2D0) +
     &             kp2*(p3p4 - ampi**2*1D0)*2D0 +
     &             p2p4*(ampi**2 + p1p3 + p2p3 - p3p4*1D0)*
     &              2D0 + ame**2*(p3p4 - ampi**2*1D0)*3D0) +
     &          kp3*(kp2*(ampi**2 - p3p4*1D0)*2D0 +
     &             ame**2*(ampi**2 - p3p4*1D0)*3D0 +
     &             p2p4*2D0*(p1p4 + p2p4 - kp4*3D0) -
     &             p2p3*2D0*
     &              (ampi**2 + p1p4 + p2p4 - p3p4*1D0 -
     &                kp4*3D0))) + ame**2*kp3**2*kp4*4D0 -
     &       ame**2*kp3*kp4**2*4D0 +
     &       ampi**2*kp4*p1p2*p1p3*4D0 -
     &       ampi**2*kp3*p1p2*p1p4*4D0 -
     &       ampi**2*kp3*p1p2*p2p3*4D0 -
     &       kp4*p1p3**2*p2p3*4D0 + kp3*p1p3*p1p4*p2p3*4D0 +
     &       kp4*p1p3*p1p4*p2p3*4D0 - kp3*p1p4**2*p2p3*4D0 -
     &       kp4*p1p3*p2p3**2*4D0 - kp3*p1p4*p2p3**2*4D0 +
     &       ampi**2*kp4*p1p2*p2p4*4D0 +
     &       kp4*p1p3**2*p2p4*4D0 - kp3*p1p3*p1p4*p2p4*4D0 -
     &       kp4*p1p3*p1p4*p2p4*4D0 + kp3*p1p4**2*p2p4*4D0 +
     &       kp4*p1p3*p2p4**2*4D0 + kp3*p1p4*p2p4**2*4D0 +
     &       p3p4*2D0*(kp4*
     &           (p1p3*(ame**2 - p1p2*2D0) +
     &             p2p4*(ame**2 - p1p2*2D0) -
     &             (ame**2 + p1p2)*p2p3*4D0) +
     &          kp3*(-((p1p4 + p2p3)*1D0*
     &                (ame**2 - p1p2*2D0)) +
     &             (ame**2 + p1p2)*p2p4*4D0)) -
     &       kp4**2*p1p2*p2p3*6D0 + kp3**2*p1p2*p2p4*6D0 +
     &       kp2*(kp4*(-(p1p3**2*2D0) -
     &             p1p3*2D0*
     &              (ampi**2 + p2p3 - p1p4*1D0 - p3p4*1D0 +
     &                p2p4*2D0) +
     &             ame**2*(ampi**2 - p3p4*1D0)*3D0 +
     &             p1p4*p2p3*6D0) +
     &          kp3*(p1p4**2*2D0 +
     &             p1p4*2D0*
     &              (ampi**2 + p2p4 - p1p3*1D0 - p3p4*1D0 +
     &                p2p3*2D0) +
     &             ame**2*(p3p4 - ampi**2*1D0)*3D0 -
     &             p1p3*p2p4*6D0)) +
     &       ame**2*ampi**2*kp4*p2p3*8D0 +
     &       ampi**2*kp4*p1p2*p2p3*8D0 +
     &       kp4*p1p4*p2p3**2*8D0 -
     &       ame**2*ampi**2*kp3*p2p4*8D0 -
     &       ampi**2*kp3*p1p2*p2p4*8D0 +
     &       kp3*p1p3*p2p3*p2p4*8D0 -
     &       kp4*p1p4*p2p3*p2p4*8D0 - kp3*p1p3*p2p4**2*8D0 +
     &       kp3*kp4*p1p2*p2p3*1.4D1 - kp3*kp4*p1p2*p2p4*1.4D1
     &       ))/(kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D1aeex340x12x15e0ee*
     &     (ame**2*kp4**2*p1p3*p2p3 + ame**2*kp4**2*p2p3**2 +
     &       ame**2*kp4**2*p1p3*p2p4 +
     &       ame**2*kp3*kp4*p1p4*p2p4 +
     &       ame**2*kp3**2*p2p3*p2p4 +
     &       ame**2*kp3*kp4*p2p4**2 -
     &       ame**2*kp3*kp4*p1p3*p2p3*1D0 -
     &       ame**2*kp3**2*p1p4*p2p3*1D0 -
     &       ame**2*kp3*kp4*p2p3**2*1D0 -
     &       ame**2*kp3**2*p1p4*p2p4*1D0 -
     &       ame**2*kp4**2*p2p3*p2p4*1D0 -
     &       ame**2*kp3**2*p2p4**2*1D0 -
     &       ame**2*kp2**2*1D0*(kp3 - kp4*1D0)*
     &        (ampi**2 - p3p4*1D0) - ame**4*kp3**2*kp4*2D0 +
     &       ame**4*kp3*kp4**2*2D0 +
     &       ame**2*kp3**2*kp4*p1p2*2D0 -
     &       ame**2*kp3*kp4**2*p1p2*2D0 +
     &       ame**2*kp3*kp4*p1p2*p1p3*2D0 -
     &       ame**2*kp4**2*p1p2*p1p3*2D0 +
     &       kp3*kp4*p1p2**2*p1p3*2D0 -
     &       kp4**2*p1p2**2*p1p3*2D0 +
     &       ame**2*kp3*kp4*p1p3**2*2D0 -
     &       ame**2*kp4**2*p1p3**2*2D0 +
     &       ame**2*kp4*p1p3**3*2D0 +
     &       ame**2*kp3**2*p1p2*p1p4*2D0 -
     &       ame**2*kp3*kp4*p1p2*p1p4*2D0 +
     &       kp3**2*p1p2**2*p1p4*2D0 -
     &       kp3*kp4*p1p2**2*p1p4*2D0 -
     &       ame**2*kp3**2*p1p3*p1p4*2D0 +
     &       ame**2*kp4**2*p1p3*p1p4*2D0 -
     &       ame**2*kp3*p1p3**2*p1p4*2D0 +
     &       ame**2*kp3**2*p1p4**2*2D0 -
     &       ame**2*kp3*kp4*p1p4**2*2D0 +
     &       ame**2*kp4*p1p3*p1p4**2*2D0 -
     &       ame**2*kp3*p1p4**3*2D0 -
     &       ame**2*kp4**2*p1p4*p2p3*2D0 -
     &       ame**2*kp4*p1p3*p2p3**2*2D0 +
     &       ame**2*kp3*p1p4*p2p3**2*2D0 +
     &       ame**2*kp3**2*p1p3*p2p4*2D0 -
     &       ame**2*kp4*p1p3*p2p4**2*2D0 +
     &       ame**2*kp3*p1p4*p2p4**2*2D0 +
     &       ame**2*kp3*kp4*p1p4*p2p3*3D0 -
     &       ame**2*kp3*kp4*p1p3*p2p4*3D0 +
     &       kp1**2*(kp4*
     &           (p1p4*p2p3*2D0 - p1p3*p2p4*2D0 +
     &             ame**2*(p3p4 - ampi**2*1D0)*3D0) +
     &          kp3*(p1p4*p2p3*2D0 - p1p3*p2p4*2D0 +
     &             ame**2*(ampi**2 - p3p4*1D0)*3D0)) -
     &       ame**4*kp3*kp4*p1p3*4D0 +
     &       ame**2*ampi**2*kp4*p1p2*p1p3*4D0 +
     &       ampi**2*kp4*p1p2**2*p1p3*4D0 +
     &       ame**4*kp3*kp4*p1p4*4D0 -
     &       ame**2*ampi**2*kp3*p1p2*p1p4*4D0 -
     &       ampi**2*kp3*p1p2**2*p1p4*4D0 -
     &       ame**2*kp4*p1p3**2*p1p4*4D0 +
     &       ame**2*kp3*p1p3*p1p4**2*4D0 -
     &       ame**4*kp3*kp4*p2p3*4D0 -
     &       kp4*p1p2*p1p3**2*p2p3*4D0 +
     &       kp3*p1p2*p1p3*p1p4*p2p3*4D0 +
     &       kp4*p1p2*p1p3*p1p4*p2p3*4D0 -
     &       kp3*p1p2*p1p4**2*p2p3*4D0 +
     &       ame**4*kp3*kp4*p2p4*4D0 +
     &       kp4*p1p2*p1p3**2*p2p4*4D0 -
     &       kp3*p1p2*p1p3*p1p4*p2p4*4D0 -
     &       kp4*p1p2*p1p3*p1p4*p2p4*4D0 +
     &       kp3*p1p2*p1p4**2*p2p4*4D0 +
     &       ame**2*kp4*p1p3*p2p3*p2p4*4D0 -
     &       ame**2*kp3*p1p4*p2p3*p2p4*4D0 -
     &       p1p2*(ame**2 + p1p2)*p3p4*
     &        (kp4*p1p3 - kp3*p1p4*1D0)*4D0 +
     &       ame**2*kp3*kp4*p1p2*p2p3*8D0 -
     &       ame**2*kp3*kp4*p1p2*p2p4*8D0 +
     &       kp2*(-(ame**2*kp3**2*1D0*(p2p4 + p1p4*5D0)) +
     &          kp4*(-((ame**2 + p1p2)*p1p3**2*2D0) +
     &             ame**2*
     &              (p2p4*(p3p4 - ampi**2*1D0) +
     &                p2p3*(ampi**2 + kp4 - p3p4*1D0) +
     &                p1p4*(p3p4 - ampi**2*1D0)*2D0) +
     &             p1p3*(p1p4*x12 +
     &                ame**2*2D0*
     &                 (p2p4 - p2p3*1D0 - ampi**2*2D0 +
     &                   p3p4*2D0) + ame**2*kp4*5D0)) +
     &          kp3*(p1p4**2*x12 +
     &             ame**2*(p2p3 - p2p4*1D0)*
     &              (ampi**2 - p3p4*1D0 - kp4*3D0) +
     &             ame**2*p1p4*
     &              (-(p2p3*2D0) + p2p4*2D0 + ampi**2*4D0 -
     &                p3p4*4D0 + kp4*9D0) +
     &             p1p3*(-((ame**2 + p1p2)*p1p4*2D0) +
     &                ame**2*(ampi**2 - p3p4*1D0)*2D0 -
     &                ame**2*kp4*9D0))) +
     &       kp1*(-(ame**2*kp2*(kp3 - kp4*1D0)*
     &             (ampi**2 - p3p4*1D0)*2D0) +
     &          kp3**2*(ame**2*p2p4 -
     &             p1p4*1D0*(p1p2*2D0 + ame**2*3D0)) +
     &          kp4*(-(p1p4**2*p2p3*2D0) +
     &             p1p3**2*(ame**2 - p2p4*1D0)*2D0 -
     &             (ame**2 + p1p2)*p1p4*(ampi**2 - p3p4*1D0)*
     &              2D0 +
     &             ame**2*
     &              (p2p4*(p3p4 - ampi**2*1D0)*3D0 +
     &                p2p3*
     &                 (-(kp4*1D0) + ampi**2*3D0 - p3p4*3D0))
     &              + p1p3*
     &              (kp4*(p1p2*2D0 + ame**2*3D0) -
     &                ampi**2*2D0*(p1p2 + ame**2*4D0) +
     &                2D0*
     &                 (p1p4*(p2p3 + p2p4 - ame**2*1D0) +
     &                   (ame**2 - p1p2*1D0)*
     &                    (p2p3 - p2p4*1D0) +
     &                   p3p4*(p1p2 + ame**2*4D0)))) +
     &          kp3*(p1p3**2*p2p4*2D0 +
     &             p1p4**2*(p2p3 - ame**2*1D0)*2D0 +
     &             ame**2*(p2p3 - p2p4*1D0)*3D0*
     &              (ampi**2 - p3p4*1D0 - kp4*5D0) +
     &             p1p4*((ame**2 - p1p2*1D0)*
     &                 (p2p3 - p2p4*1D0)*2D0 +
     &                ampi**2*2D0*(p1p2 + ame**2*4D0) -
     &                p3p4*2D0*(p1p2 + ame**2*4D0) +
     &                kp4*(p1p2*6D0 + ame**2*1.7D1)) +
     &             p1p3*(ampi**2*x12 -
     &                (ame**2 + p1p2)*p3p4*2D0 +
     &                p1p4*(ame**2 - p2p3*1D0 - p2p4*1D0)*
     &                 2D0 - kp4*1D0*(p1p2*6D0 + ame**2*1.7D1)
     &                )))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D12aeex340x12x15e0ee*
     &     (ame**2*kp3*kp4*p1p3**2 +
     &       ame**2*kp4**2*p1p3*p1p4 +
     &       ame**2*kp3**2*p1p4**2 + ame**2*kp4**2*p2p3**2 -
     &       ame**2*kp4**2*p1p3**2*1D0 -
     &       ame**2*kp3**2*p1p3*p1p4*1D0 -
     &       ame**2*kp3*kp4*p1p4**2*1D0 -
     &       ame**2*kp3**2*p1p4*p2p3*1D0 -
     &       ame**2*kp4**2*p1p4*p2p3*1D0 -
     &       ame**2*kp3*kp4*p2p3**2*1D0 +
     &       ame**2*kp4*p1p3**2*p2p3*2D0 +
     &       ame**2*kp3*kp4*p1p4*p2p3*2D0 -
     &       kp3**2*p1p2*p1p4*p2p3*2D0 -
     &       kp4**2*p1p2*p1p4*p2p3*2D0 +
     &       ame**2*kp3*p1p3*p1p4*p2p3*2D0 -
     &       ame**2*kp3*p1p4**2*p2p3*2D0 +
     &       ame**2*kp4*p1p4*p2p3**2*2D0 -
     &       ame**2*kp4*p2p3**3*2D0 +
     &       ame**2*kp3*p2p4**3*2D0 +
     &       kp3*kp4*p1p2*p1p4*p2p3*4D0 +
     &       ame**2*kp4*p1p4**2*p2p3*4D0 +
     &       kp1**2*(kp3 + kp4)*(p1p4*p2p3 - p1p3*p2p4*1D0)*
     &        4D0 - ame**2*kp4*p1p3*p1p4*p2p3*6D0 +
     &       ame**2*kp3*p1p4*p2p3**2*6D0 +
     &       p2p4*(kp3**2*
     &           (ame**2*p2p3 + p1p3*(ame**2 + p1p2*2D0)) +
     &          kp4*(p1p3*
     &              (ame**2*(p1p3 - p1p4*1D0)*2D0 +
     &                kp4*(ame**2 + p1p2*2D0)) +
     &             ame**2*p2p3**2*4D0 -
     &             ame**2*p2p3*1D0*
     &              (kp4 + 2D0*(p1p4 - p1p3*7D0))) +
     &          kp3*2D0*(kp4*
     &              (-(p1p3*1D0*(ame**2 + p1p2*2D0)) +
     &                ame**4*4D0 - ame**2*p1p2*4D0) +
     &             ame**2*
     &              (p2p3**2 - p1p4**2*1D0 - p1p3**2*2D0 +
     &                p1p3*p1p4*3D0 + p2p3*(p1p3 - p1p4*7D0)))
     &          ) - ame**4*kp3*kp4*p1p3*8D0 +
     &       ame**2*kp3*kp4*p1p2*p1p3*8D0 +
     &       ame**2*kp4*p1p3**3*8D0 +
     &       ame**4*kp3*kp4*p1p4*8D0 -
     &       ame**2*kp3*kp4*p1p2*p1p4*8D0 -
     &       ame**2*kp3*p1p3**2*p1p4*8D0 +
     &       ame**2*kp4*p1p3*p1p4**2*8D0 -
     &       ame**2*kp3*p1p4**3*8D0 -
     &       ame**4*kp3*kp4*p2p3*8D0 +
     &       ame**2*kp3*kp4*p1p2*p2p3*8D0 -
     &       ame**2*kp4*p1p3*p2p3**2*8D0 -
     &       ame**2*p2p4**2*1D0*
     &        (kp3**2 + kp4*2D0*(p2p3 + p1p3*3D0) -
     &          kp3*1D0*(kp4 - p1p3*2D0 - p2p3*4D0 + p1p4*8D0)
     &          ) + kp2*(-(kp3**2*2D0*
     &             (ame**2*p2p4 +
     &               p1p4*(p1p2*2D0 + ame**2*3D0))) +
     &          kp4*(-(p1p4**2*p2p3*2D0) +
     &             ame**2*
     &              (p2p4*(p3p4 - ampi**2*1D0) -
     &                p2p3**2*2D0 +
     &                p2p3*
     &                 (p3p4 - ampi**2*1D0 + kp4*2D0 +
     &                   p2p4*2D0)) -
     &             p1p3**2*2D0*(p2p4 + ame**2*4D0) +
     &             p1p4*(p1p2*(p3p4 - ampi**2*1D0)*4D0 +
     &                ame**2*
     &                 (p2p3*4D0 - ampi**2*5D0 + p3p4*5D0)) +
     &             p1p3*(p1p2*(p3p4 - ampi**2*1D0)*4D0 +
     &                p1p4*2D0*(p2p3 + p2p4 + ame**2*4D0) +
     &                kp4*(p1p2*4D0 + ame**2*6D0) +
     &                ame**2*
     &                 (-(ampi**2*5D0) + p3p4*5D0 +
     &                   p2p4*6D0 - p2p3*1.D1))) +
     &          kp3*(p1p3**2*p2p4*2D0 +
     &             p1p4**2*2D0*(p2p3 + ame**2*4D0) +
     &             ame**2*
     &              (p2p3*
     &                 (ampi**2 - p3p4*1D0 - p2p4*2D0 -
     &                   kp4*1.D1) +
     &                p2p4*
     &                 (ampi**2 - p3p4*1D0 + p2p4*2D0 +
     &                   kp4*1.D1)) +
     &             p1p3*(p1p2*(ampi**2 - p3p4*1D0)*4D0 -
     &                p1p4*2D0*(p2p3 + p2p4 + ame**2*4D0) +
     &                ame**2*
     &                 (-(p2p4*4D0) + ampi**2*5D0 - p3p4*5D0)
     &                 - kp4*2D0*(p1p2*6D0 + ame**2*1.1D1)) +
     &             p1p4*(p1p2*(ampi**2 - p3p4*1D0)*4D0 +
     &                ame**2*
     &                 (ampi**2*5D0 - p3p4*5D0 - p2p3*6D0 +
     &                   p2p4*1.D1) +
     &                kp4*2D0*(p1p2*6D0 + ame**2*1.1D1)))) -
     &       ame**2*kp4*p1p3**2*p1p4*1.6D1 +
     &       ame**2*kp3*p1p3*p1p4**2*1.6D1 +
     &       kp1*(-(kp3**2*(ame**2 + p1p2)*2D0*
     &             (p2p4 + p1p4*2D0)) +
     &          kp4*(ame**2*kp4*p2p3*2D0 -
     &             ampi**2*p1p2*p2p3*2D0 +
     &             kp4*p1p2*p2p3*2D0 + ame**2*p2p3**2*2D0 -
     &             ampi**2*p1p2*p2p4*2D0 -
     &             ame**2*p2p3*p2p4*2D0 -
     &             ame**2*ampi**2*p2p3*3D0 -
     &             ame**2*ampi**2*p2p4*3D0 +
     &             (p2p3 + p2p4)*p3p4*
     &              (p1p2*2D0 + ame**2*3D0) -
     &             p1p4**2*p2p3*4D0 -
     &             p1p4*1D0*
     &              (p2p3*2D0*
     &                 (kp2 + (ame**2 + p2p3 - p2p4*1D0)*2D0)
     &                 + p1p2*(ampi**2 - p3p4*1D0)*4D0 +
     &                ame**2*ampi**2*5D0 - ame**2*p3p4*5D0) +
     &             p1p3**2*(-(p2p4*4D0) + ame**2*8D0) +
     &             p1p3*(p2p4*2D0*
     &                 (kp2 + p2p3*2D0 - ame**2*3D0) +
     &                kp4*(ame**2 + p1p2)*4D0 - p2p4**2*4D0 +
     &                p1p4*(p2p3 + p2p4 - ame**2*2D0)*4D0 +
     &                p3p4*(p1p2*4D0 + ame**2*5D0) -
     &                ampi**2*1D0*(p1p2*4D0 + ame**2*5D0) +
     &                ame**2*p2p3*1.D1)) +
     &          kp3*(ampi**2*p1p2*p2p3*2D0 +
     &             ampi**2*p1p2*p2p4*2D0 +
     &             ame**2*p2p3*p2p4*2D0 -
     &             ame**2*p2p4**2*2D0 +
     &             ame**2*ampi**2*p2p3*3D0 +
     &             ame**2*ampi**2*p2p4*3D0 -
     &             (p2p3 + p2p4)*p3p4*1D0*
     &              (p1p2*2D0 + ame**2*3D0) +
     &             p1p3**2*p2p4*4D0 +
     &             p1p4**2*(p2p3 - ame**2*2D0)*4D0 -
     &             kp4*p1p2*p2p3*6D0 + kp4*p1p2*p2p4*6D0 +
     &             p1p4*(p2p3**2*4D0 +
     &                p1p2*(ampi**2 - p3p4*1D0)*4D0 +
     &                ame**2*(ampi**2 - p3p4*1D0 - p2p4*2D0)*
     &                 5D0 +
     &                p2p3*
     &                 (-(kp2*2D0) - p2p4*4D0 + ame**2*6D0) +
     &                kp4*4D0*(p1p2*3D0 + ame**2*8D0)) +
     &             p1p3*(p2p4*2D0*
     &                 (kp2 + (ame**2 + p2p4 - p2p3*1D0)*2D0)
     &                 + p1p2*(ampi**2 - p3p4*1D0)*4D0 +
     &                ame**2*ampi**2*5D0 - ame**2*p3p4*5D0 -
     &                kp4*4D0*(p1p2*3D0 + ame**2*8D0) +
     &                p1p4*
     &                 (-(p2p3*4D0) - p2p4*4D0 + ame**2*8D0))
     &              - ame**2*kp4*p2p3*2.6D1 +
     &             ame**2*kp4*p2p4*2.6D1))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (D2aeex340x12x15e0ee*
     &     (2D0*(-(kp4**2*1D0*
     &             (p1p2**2*(p1p3 + p2p3) +
     &               ame**2*
     &                (p1p3**2 - p1p3*p1p4*1D0 +
     &                  p2p3*(p2p4 - p2p3*1D0)) +
     &               p1p2*
     &                ((ame**2 + p1p4)*p2p3 +
     &                  p1p3*(ame**2 - p2p4*1D0)))) +
     &          kp3*(ame**2*
     &              (kp3*
     &                 (p1p4**2 - p1p3*p1p4*1D0 +
     &                   p2p4*(p2p3 - p2p4*1D0)) -
     &                (p1p4 + p2p4)*1D0*
     &                 ((p1p3 - p1p4*1D0)**2 -
     &                   1D0*(p2p3 - p2p4*1D0)**2)) -
     &             p1p2**2*(p1p4 + p2p4)*1D0*
     &              (-(kp3*1D0) + ampi**2*2D0 - p3p4*2D0) +
     &             p1p2*(p1p4**2*(p2p4 - p2p3*1D0)*2D0 +
     &                p2p4*
     &                 (kp3*(ame**2 + p1p3) +
     &                   ame**2*(p3p4 - ampi**2*1D0)*2D0 +
     &                   p1p3*(p2p3 - p2p4*1D0)*2D0) +
     &                p1p4*
     &                 (kp3*(ame**2 - p2p3*1D0) +
     &                   ame**2*(p3p4 - ampi**2*1D0)*2D0 +
     &                   (p1p3 - p2p4*1D0)*(p2p3 - p2p4*1D0)*
     &                    2D0))) +
     &          kp4*(ame**2*
     &              (kp3*
     &                 (p1p3**2 + p2p4**2 - p1p4**2*1D0 -
     &                   p2p3**2*1D0) +
     &                (p1p3 + p2p3)*
     &                 ((p1p3 - p1p4*1D0)**2 -
     &                   1D0*(p2p3 - p2p4*1D0)**2)) +
     &             p1p2**2*
     &              (-(kp3*1D0*(p1p4 + p2p4 - p2p3*1D0)) +
     &                p2p3*(ampi**2 - p3p4*1D0)*2D0 +
     &                p1p3*(kp3 + ampi**2*2D0 - p3p4*2D0)) +
     &             p1p2*(p1p3**2*(p2p4 - p2p3*1D0)*2D0 +
     &                p2p3*
     &                 (p1p4*(p2p3 - p2p4*1D0) +
     &                   ame**2*(ampi**2 - p3p4*1D0))*2D0 +
     &                kp3*
     &                 (ame**2*(p2p3 - p2p4*1D0) -
     &                   p1p4*1D0*(ame**2 - p2p3*2D0)) +
     &                p1p3*
     &                 ((p1p4 - p2p3*1D0)*(p2p3 - p2p4*1D0)*
     &                    2D0 +
     &                   ame**2*(ampi**2 - p3p4*1D0)*2D0 +
     &                   kp3*(ame**2 - p2p4*2D0))))) -
     &       ame**2*kp2**2*(kp3 - kp4*1D0)*
     &        (ampi**2 - p3p4*1D0)*3D0 +
     &       kp1**2*(kp4*
     &           (p1p4*p2p3*2D0 - p1p3*p2p4*2D0 +
     &             ame**2*(p3p4 - ampi**2*1D0)*3D0) +
     &          kp3*(p1p4*p2p3*2D0 - p1p3*p2p4*2D0 +
     &             ame**2*(ampi**2 - p3p4*1D0)*3D0)) +
     &       kp1*(kp3**2*
     &           (p2p4*(ame**2 + p1p2*2D0) -
     &             p1p4*1D0*(p1p2*2D0 + ame**2*3D0)) +
     &          kp4*(-(ame**2*kp4*p2p3*1D0) +
     &             ame**2*ampi**2*p2p3*2D0 +
     &             ampi**2*p1p2*p2p3*2D0 -
     &             kp4*p1p2*p2p3*2D0 - p1p4**2*p2p3*2D0 +
     &             ame**2*p2p3**2*2D0 - p1p2*p2p3**2*2D0 +
     &             ampi**2*p1p2*p2p4*2D0 -
     &             ame**2*p2p3*p2p4*2D0 +
     &             p1p2*p2p3*p2p4*2D0 +
     &             p1p3**2*(ame**2 - p2p4*1D0)*2D0 +
     &             p1p4*(p2p3*(kp2 - ame**2*1D0) +
     &                ame**2*(p3p4 - ampi**2*1D0) +
     &                p1p2*(p3p4 - ampi**2*1D0))*2D0 -
     &             p3p4*2D0*
     &              ((ame**2 + p1p2)*p2p3 +
     &                p2p4*(p1p2 - ame**2*2D0)) -
     &             ame**2*ampi**2*p2p4*4D0 +
     &             p1p3*(kp4*(p1p2*2D0 + ame**2*3D0) +
     &                2D0*
     &                 (-(p1p2*(ampi**2 + p2p3)*1D0) +
     &                   p2p4*
     &                    (p1p2 + p1p4 - ame**2*1D0 - kp2*1D0)
     &                     + p2p3*(p1p4 + ame**2*2D0) +
     &                   p3p4*(p1p2 + ame**2*4D0) -
     &                   ame**2*1D0*(p1p4 + ampi**2*4D0)))) +
     &          kp3*(-(ampi**2*p1p2*p2p3*2D0) -
     &             ame**2*ampi**2*p2p4*2D0 -
     &             ampi**2*p1p2*p2p4*2D0 + p1p3**2*p2p4*2D0 +
     &             ame**2*p2p3*p2p4*2D0 -
     &             p1p2*p2p3*p2p4*2D0 - ame**2*p2p4**2*2D0 +
     &             p1p2*p2p4**2*2D0 +
     &             p1p4**2*(p2p3 - ame**2*1D0)*2D0 +
     &             p3p4*2D0*
     &              ((ame**2 + p1p2)*p2p4 +
     &                p2p3*(p1p2 - ame**2*2D0)) +
     &             ame**2*ampi**2*p2p3*4D0 +
     &             kp4*p1p2*p2p3*6D0 - kp4*p1p2*p2p4*6D0 -
     &             ame**2*kp4*p2p3*1.7D1 +
     &             ame**2*kp4*p2p4*1.7D1 +
     &             p1p4*((ame**2 + kp2)*p2p3*2D0 +
     &                p1p2*
     &                 (ampi**2 + p2p4 - p2p3*1D0 - p3p4*1D0)*
     &                 2D0 +
     &                ame**2*
     &                 (-(p2p4*1D0) + ampi**2*2D0 - p3p4*2D0)*
     &                 4D0 + kp4*(p1p2*6D0 + ame**2*1.7D1)) +
     &             p1p3*(ampi**2*x12 -
     &                (ame**2 + p1p2)*p3p4*2D0 +
     &                p2p4*(ame**2 - kp2*1D0)*2D0 +
     &                p1p4*(ame**2 - p2p3*1D0 - p2p4*1D0)*
     &                 2D0 - kp4*1D0*(p1p2*6D0 + ame**2*1.7D1)
     &                ))) +
     &       kp2*(-(kp3**2*1D0*
     &             (ame**2*p2p4*5D0 +
     &               p1p4*(p1p2*4D0 + ame**2*9D0))) +
     &          kp4*(-(p1p4**2*p2p3*2D0) -
     &             p1p3**2*(ame**2 + p1p2 + p2p4)*2D0 -
     &             (ame**2 + p1p2)*p1p4*2D0*
     &              (-(p2p3*1D0) + ampi**2*2D0 - p3p4*2D0) +
     &             ame**2*
     &              (p2p3*
     &                 (-(p2p3*2D0) + p2p4*2D0 + kp4*5D0) -
     &                ampi**2*p2p4*6D0 + p2p4*p3p4*6D0) +
     &             p1p3*(2D0*
     &                 (p1p4*(ame**2 + p2p3 + p2p4) +
     &                   p1p2*
     &                    (p1p4 - p2p3*1D0 - ampi**2*2D0 +
     &                     p3p4*2D0) +
     &                   ame**2*
     &                    (p2p4 - p2p3*2D0 - ampi**2*5D0 +
     &                     p3p4*5D0)) +
     &                kp4*(p1p2*4D0 + ame**2*9D0))) +
     &          kp3*(p1p4**2*(ame**2 + p1p2 + p2p3)*2D0 +
     &             p1p3**2*p2p4*2D0 +
     &             p1p3*(-(p1p4*(ame**2 + p1p2 + p2p3 + p2p4)*
     &                   2D0) -
     &                (ame**2 + p1p2)*2D0*(p2p4 + p3p4*2D0) +
     &                ampi**2*(ame**2 + p1p2)*4D0 -
     &                kp4*3D0*(p1p2*4D0 + ame**2*9D0)) +
     &             p1p4*(p1p2*2D0*
     &                 (p2p4 + ampi**2*2D0 - p3p4*2D0) +
     &                ame**2*2D0*
     &                 (-(p2p3*1D0) + p2p4*2D0 +
     &                   ampi**2*5D0 - p3p4*5D0) +
     &                kp4*3D0*(p1p2*4D0 + ame**2*9D0)) +
     &             ame**2*
     &              (p2p3*
     &                 (-(p2p4*2D0) + ampi**2*6D0 -
     &                   p3p4*6D0 - kp4*2.7D1) +
     &                p2p4*(p2p4*2D0 + kp4*2.7D1))))))/
     &   (kp3*kp4*(ame**2 + p1p2)*(ampi**2 + p3p4))
