#!/bin/bash

s1=1
until [ $s1 -eq 0 ]; do
 if [ -f process_$s1.tex ]; then
  latex  process_$s1.tex
  dvips  process_$s1.dvi -o
  ps2pdf process_$s1.ps
  rm process_$s1.aux process_$s1.dvi process_$s1.log process_$s1.ps;
  s1=`expr $s1 + 1`
 else
  s1=0
 fi
done

exit


