        elmat3 = -((ame**2*C1aex34x15e00*1D0*
     &       (kp3*kp4*p1p3 + kp3*kp4*p1p4 + kp3*kp4*p2p3 -
     &         kp4**2*p1p3*1D0 - kp3**2*p1p4*1D0 -
     &         kp4**2*p2p3*1D0 - kp4*p1p3**2*2D0 +
     &         kp3*p1p3*p1p4*2D0 + kp4*p1p3*p1p4*2D0 -
     &         kp3*p1p4**2*2D0 + kp4*p1p3*p2p3*2D0 -
     &         kp3*p1p4*p2p3*2D0 +
     &         p2p4*(-(kp3**2*1D0) - kp4*p1p3*2D0 +
     &            kp3*(kp4 + p1p4*2D0)) +
     &         ame**2*kp3*kp4*4D0 - kp3*kp4*p1p2*4D0 +
     &         kp1*(kp4*(p3p4 - ampi**2*1D0 - p1p3*2D0) +
     &            kp3*(p3p4 - ampi**2*1D0 - p1p4*2D0 +
     &               kp4*4D0)) +
     &         kp2*(kp4*(p3p4 - ampi**2*1D0 + p1p3*2D0) +
     &            kp3*(p3p4 - ampi**2*1D0 + p1p4*2D0 +
     &               kp4*4D0))))/(kp1*kp3*kp4*(ame**2 + p1p2))
     &     ) - (ame**2*C0aex15x340e0*2D0*
     &     (kp3*kp4*p1p3 + kp3*kp4*p1p4 + kp3*kp4*p2p3 -
     &       kp4**2*p1p3*1D0 - kp3**2*p1p4*1D0 -
     &       kp4**2*p2p3*1D0 - kp4*p1p3**2*2D0 +
     &       kp3*p1p3*p1p4*2D0 + kp4*p1p3*p1p4*2D0 -
     &       kp3*p1p4**2*2D0 + kp4*p1p3*p2p3*2D0 -
     &       kp3*p1p4*p2p3*2D0 +
     &       p2p4*(-(kp3**2*1D0) - kp4*p1p3*2D0 +
     &          kp3*(kp4 + p1p4*2D0)) + ame**2*kp3*kp4*4D0 -
     &       kp3*kp4*p1p2*4D0 +
     &       kp1*(kp4*(p3p4 - ampi**2*1D0 - p1p3*2D0) +
     &          kp3*(p3p4 - ampi**2*1D0 - p1p4*2D0 + kp4*4D0))
     &         + kp2*(kp4*(p3p4 - ampi**2*1D0 + p1p3*2D0) +
     &          kp3*(p3p4 - ampi**2*1D0 + p1p4*2D0 + kp4*4D0))
     &       ))/(kp1*kp3*kp4*(ame**2 + p1p2)) +
     &  (C1ax15x34ee00*(kp1**2*(kp4*p2p3 + kp3*p2p4)*2D0 +
     &       kp1*(kp4*(ame**2*(p3p4 - ampi**2*1D0) -
     &             p1p4*p2p3*2D0 +
     &             p1p2*(p3p4 - ampi**2*1D0)*2D0 +
     &             p1p3*2D0*
     &              (ame**2 + kp2 - p2p4*1D0 + p2p3*2D0)) +
     &          kp3*(-(p1p3*p2p4*2D0) +
     &             p3p4*(ame**2 + p1p2*2D0) -
     &             ampi**2*1D0*(ame**2 + p1p2*2D0) +
     &             p1p4*2D0*
     &              (ame**2 + kp2 - p2p3*1D0 + p2p4*2D0) +
     &             kp4*(p1p2 + ame**2*2D0)*4D0)) -
     &       ame**2*1D0*(-(kp3**2*(p1p4 + p2p4)*1D0) -
     &          kp4*1D0*(kp4*(p1p3 + p2p3) +
     &             p1p3*(p1p3 + p2p4 - p1p4*1D0 - p2p3*1D0)*
     &              2D0) +
     &          kp2*(kp4*(p3p4 - ampi**2*1D0 + p1p3*2D0) +
     &             kp3*(p3p4 - ampi**2*1D0 + p1p4*2D0 +
     &                kp4*4D0)) +
     &          kp3*(p1p4*(p1p3 + p2p4 - p1p4*1D0 - p2p3*1D0)*
     &              2D0 +
     &             kp4*(p1p3 + p1p4 + p2p3 + p2p4 +
     &                ame**2*4D0 - p1p2*4D0)))))/
     &   (kp1*kp3*kp4*(ame**2 + p1p2))

