        elmat1 = (ame**2*C0aeex120e0*
     &     (kp3*p3p4*(kp2 + p1p3 + p2p4 - kp1*1D0 -
     &          p1p4*1D0 - p2p3*1D0) +
     &       kp4*(ampi**2*kp2 + ampi**2*p1p4 + ampi**2*p2p3 -
     &          ampi**2*kp1*1D0 - ampi**2*p1p3*1D0 -
     &          ampi**2*p2p4*1D0 + kp3*p1p3*2D0 - kp3*p2p3*2D0
     &          ))*4D0)/(kp3**2*kp4*(ame**2 + p1p2)) +
     &  (ame**2*C1aex12ee00*
     &     (kp3*p3p4*(kp2 + p1p3 + p2p4 - kp1*1D0 -
     &          p1p4*1D0 - p2p3*1D0) +
     &       kp4*(ampi**2*kp2 + ampi**2*p1p4 + ampi**2*p2p3 -
     &          ampi**2*kp1*1D0 - ampi**2*p1p3*1D0 -
     &          ampi**2*p2p4*1D0 + kp3*p1p3*2D0 - kp3*p2p3*2D0
     &          ))*4D0)/(kp3**2*kp4*(ame**2 + p1p2))
