        elmat = (CONJG(ffpiis)*ffpiintk*
     &    (p2p3*(ame**2*(kp2 + p1p4 - kp4*1D0 - p1p2*1D0 -
     &            ame**2*2D0) +
     &         kp1*(kp2 - kp4*1D0 + ame**2*2D0)) +
     &      p2p4*(kp1*(kp3 - kp2*1D0 - ame**2*2D0) +
     &         ame**2*(kp3 + p1p2 - kp2*1D0 - p1p3*1D0 +
     &            ame**2*2D0))))/
     &  (kp1**2*(ampi**2 + p3p4)*(ampi**2 + p3p4 + p3q + p4q)*
     &    (ampi**2 + p3p4 - p2p3*1D0 - p2p4*1D0))

