        elmat = -((CONJG(ffpiintk)*ffpifs*(ampi**2 + p3q)*5.D-1*
     &      (kq*p1p2 + ame**2*p1p3 + kp2*p1p3 + ame**2*p1q +
     &        kp2*p1q + ame**2*p2p4 + kp1*p2p4 -
     &        ame**2*p1p4*1D0 - kp2*p1p4*1D0 -
     &        ame**2*p2p3*1D0 - kp1*p2p3*1D0 -
     &        ame**2*p2q*1D0 - kp1*p2q*1D0 + ame**2*kq*2D0 +
     &        kp3*(p1p2 + ame**2*2D0) -
     &        kp4*1D0*(p1p2 + ame**2*2D0)))/
     &    (kp2*(ame**2 + p1p2)*p3q**2*
     &      (ampi**2 + p3p4 + p3q + p4q)))
