        elmat = -((CONJG(ffpifs)*ampi**2*ffpifs*(ampi**2 + p3q)*
     &      5.D-1*(ame**2*ampi**2 + ame**2*kp4 +
     &        ampi**2*p1p2 + kp4*p1p2 + kp2*p1p3 + kp2*p1q +
     &        p1p4*p2p3 + p1p3*p2p4 + p1q*p2p4 + p1p4*p2q +
     &        ame**2*p3q + p1p2*p3q - ame**2*kq*1D0 -
     &        kq*p1p2*1D0 - kp3*(ame**2 + p1p2)*1D0 -
     &        kp2*p1p4*1D0 - p1p3*p2p3*1D0 - p1q*p2p3*1D0 -
     &        p1p4*p2p4*1D0 - p1p3*p2q*1D0 - p1q*p2q*1D0 -
     &        ame**2*p3p4*1D0 - p1p2*p3p4*1D0 -
     &        ame**2*p4q*1D0 - p1p2*p4q*1D0 +
     &        kp1*(p2p3 + p2q - kp2*1D0 - p2p4*1D0)))/
     &    (kp4**2*(ame**2 + p1p2)**2*p3q**2))
