        elmat = (CONJG(ffpiis)*ffpiintk*5.D-1*
     &    (ame**2*kq*p1p3 + kp2*kq*p1p3 + ame**4*p1p4 +
     &      kp2**2*p1p4 + ame**4*p2p3 + ame**2*p1q*p2p3 +
     &      kp1*kp2*p2p4 + ame**2*p1p4*p2q + ame**2*kp1*p3q +
     &      kp1*kp2*p3q + ame**2*p1p2*p4q - ame**4*p1p3*1D0 -
     &      kp2**2*p1p3*1D0 - ame**2*kq*p1p4*1D0 -
     &      kp2*kq*p1p4*1D0 - kp1*kp2*p2p3*1D0 -
     &      ame**4*p2p4*1D0 - ame**2*p1q*p2p4*1D0 -
     &      ame**2*p1p3*p2q*1D0 - ame**2*p1p2*p3q*1D0 -
     &      ame**2*kp1*p4q*1D0 - kp1*kp2*p4q*1D0 -
     &      ame**2*kp2*p2p3*2D0 + ame**2*kp2*p2p4*2D0 -
     &      ame**4*p3q*2D0 + ame**2*kp2*p3q*2D0 +
     &      ame**4*p4q*2D0 - ame**2*kp2*p4q*2D0 +
     &      kp4*(ame**2*(ame**2 + p1q) +
     &         kp2*(p1q - p1p2*1D0 - ame**2*3D0)) -
     &      kp3*1D0*(ame**2*(ame**2 + p1q) +
     &         kp2*(p1q - p1p2*1D0 - ame**2*3D0))))/
     &  (kp2**2*(ampi**2 + p3p4)*(ampi**2 + p3p4 + p3q + p4q)*
     &    (kp2 + p2q - kq*1D0))

