        elmat = (CONJG(ffpiintq)*ffpifs*5.D-1*
     &    (ame**2*kq + kq*p1p2 + ame**2*p1p3 + p1q*p2p3 +
     &      ame**2*p2p4 + ame**2*p2q + p1p3*p2q +
     &      ame**2*p4q + p1p2*p4q - ame**2*p1p4*1D0 -
     &      ame**2*p1q*1D0 - ame**2*p2p3*1D0 - p1q*p2p4*1D0 -
     &      p1p4*p2q*1D0 - kp1*(ame**2 + p2q)*1D0 -
     &      ame**2*p3q*1D0 - p1p2*p3q*1D0 +
     &      kp2*(ame**2 - p1q*1D0) - p1q*p2q*2D0))/
     &  ((ame**2 + p1p2)*p2q*(ampi**2 + kp3 + kp4 + p3p4)*
     &    (kp4 + kq + p4q))
