        elmat = (CONJG(ffpiintq)*ffpifs*2.5D-1*
     &    (ampi**2*p1q*p2p3 + ampi**2*p1q*p2p4 +
     &      ampi**2*kp1*p2q + ampi**2*p1p4*p2q +
     &      kp1*p2p4*p2q + ame**2*p2q*p3p4 + p1p2*p2q*p3p4 +
     &      ame**2*ampi**2*p4q + ampi**2*p1p2*p4q -
     &      ame**2*ampi**2*p2q*1D0 - ame**2*kp4*p2q*1D0 -
     &      ampi**2*p1p2*p2q*1D0 - kp4*p1p2*p2q*1D0 -
     &      ampi**2*p1p3*p2q*1D0 - p1p4*p2p3*p2q*1D0 -
     &      p1p3*p2p4*p2q*1D0 - ame**2*ampi**2*p3q*1D0 -
     &      ampi**2*p1p2*p3q*1D0 - ame**2*ampi**2*p2p4*2D0 -
     &      ame**2*kp4*p2p4*2D0 - ampi**2*p1p2*p2p4*2D0 -
     &      kp4*p1p2*p2p4*2D0 + kp4*p1q*p2p4*2D0 -
     &      p1p4*p2p3*p2p4*2D0 + kp1*p2p4**2*2D0 -
     &      p1p3*p2p4**2*2D0 + p1p4*p2p4*p2q*2D0 +
     &      ame**2*p2p4*p3p4*2D0 + p1p2*p2p4*p3p4*2D0 -
     &      p1q*p2p4*p3p4*2D0 + p1p4*p2p4*p3q*2D0 -
     &      kp1*p2p4*p4q*2D0 + p1p3*p2p4*p4q*2D0 +
     &      kq*(ame**2*ampi**2 + ampi**2*p1p2 -
     &         p1p4*p2p4*2D0) +
     &      kp2*(-(ampi**2*p1q*1D0) +
     &         p1p4*(p2q + p2p4*2D0)) + p1p4*p2p4**2*4D0 -
     &      p1p4*p2p4*p4q*4D0))/
     &  (kp4*(ame**2 + p1p2)*p2q*(ampi**2 + kp3 + kp4 + p3p4)*
     &    p4q)
