        elmat = (CONJG(ffpiis)*ffpifs*5.D-1*
     &    (ame**2*p2p3*p2p4 + p1q*p2p3*p2p4 +
     &      ampi**2*p1p4*(ame**2 + p2q) + ame**2*p2p3*p3p4 +
     &      p1q*p2p3*p3p4 + p1p2*p2p4*p3q + p1p2*p3p4*p3q -
     &      ame**2*p2p3**2*1D0 - p1q*p2p3**2*1D0 -
     &      ame**2*ampi**2*p2p4*1D0 - ampi**2*p1q*p2p4*1D0 -
     &      p1p2*p2p3*p3q*1D0 - ampi**2*p1p2*p4q*1D0 +
     &      p1p3*(ame**2 + p2q)*
     &       (p2p3 - p2p4*1D0 - p3p4*1D0) -
     &      ame**2*p2p3*p3q*2D0 + ame**2*p2p4*p3q*2D0 +
     &      ame**2*p3p4*p3q*2D0 - ame**2*ampi**2*p4q*2D0))/
     &  (kp3*(ame**2 + p1p2)*p1q*(ampi**2 + p3p4)*
     &    (ampi**2 + p3p4 - p2p3*1D0 - p2p4*1D0))

