        elmat = -((CONJG(ffpiintq)*ffpiintq*p3p4*5.D-1*
     &      (ame**2*ampi**2*p1q + ame**2*p1p3*p2p3 +
     &        ame**2*p1p4*p2p4 + ame**2*ampi**2*p2q +
     &        ampi**2*p1q*p2q + ame**4*p3p4 +
     &        ame**2*p1p4*p3q + p1p4*p2q*p3q +
     &        ame**2*p1p3*p4q + p1p3*p2q*p4q -
     &        ame**4*ampi**2*1D0 - ame**2*p1p4*p2p3*1D0 -
     &        ame**2*p1p3*p2p4*1D0 - ame**2*p1q*p3p4*1D0 -
     &        ame**2*p2q*p3p4*1D0 - p1q*p2q*p3p4*1D0 -
     &        ame**2*p1p3*p3q*1D0 - p1p3*p2q*p3q*1D0 -
     &        ame**2*p1p4*p4q*1D0 - p1p4*p2q*p4q*1D0 +
     &        ame**2*p1p2*(p3p4 - ampi**2*1D0) +
     &        kp1*(kq*(ame**2 + p2q) - ame**2*kp2*1D0)))/
     &    (kp3*kp4*p2q**2*(ampi**2 + kp3 + kp4 + p3p4)**2))
