        elmat = (CONJG(ffpifs)*ffpifs*p3p4*2.5D-1*
     &    (kq*(ame**2 + p1p2) + ame**2*p4q + p1p2*p4q -
     &      kp2*p1q*1D0 - p1q*p2p4*1D0 - kp1*p2q*1D0 -
     &      p1p4*p2q*1D0 - ame**2*ampi**2*2D0 -
     &      ampi**2*p1p2*2D0 + kp3*(ame**2 + p1p2)*2D0 -
     &      kp2*p1p3*2D0 - kp1*p2p3*2D0 - p1p4*p2p3*2D0 -
     &      p1p3*p2p4*2D0 + p1q*p2q*2D0 + ame**2*p3p4*2D0 +
     &      p1p2*p3p4*2D0 + p1q*p2p3*3D0 + p1p3*p2q*3D0 -
     &      ame**2*p3q*3D0 - p1p2*p3q*3D0 + p1p3*p2p3*4D0))/
     &  (kp3*kp4*(ame**2 + p1p2)**2*p3q)
