        elmat = -((CONJG(ffpiintq)*ampi**2*ffpiintq*5.D-1*
     &      (ame**4*ampi**2 + ame**4*kp4 + ame**2*kp2*kq +
     &        ame**2*ampi**2*p1p2 + ame**2*kp4*p1p2 +
     &        ame**2*kp2*p1p3 + kp2*kq*p1q +
     &        ame**2*p1p4*p2p3 + ame**2*kq*p2p4 +
     &        ame**2*p1p3*p2p4 + kq*p1q*p2p4 +
     &        ame**2*p1q*p3p4 + ame**2*p2q*p3p4 +
     &        p1q*p2q*p3p4 + ame**2*p2p3*p3q + p1q*p2p3*p3q +
     &        ame**2*kp2*p4q + kp2*p1q*p4q +
     &        ame**2*p2p4*p4q + p1q*p2p4*p4q -
     &        ame**2*kp2*p1p4*1D0 - ame**2*ampi**2*p1q*1D0 -
     &        ame**2*kp4*p1q*1D0 - ame**2*kq*p2p3*1D0 -
     &        ame**2*p1p3*p2p3*1D0 - kq*p1q*p2p3*1D0 -
     &        ame**2*p1p4*p2p4*1D0 - ame**2*ampi**2*p2q*1D0 -
     &        ame**2*kp4*p2q*1D0 - ampi**2*p1q*p2q*1D0 -
     &        kp4*p1q*p2q*1D0 - ame**4*p3p4*1D0 -
     &        ame**2*p1p2*p3p4*1D0 - ame**2*kp2*p3q*1D0 -
     &        kp2*p1q*p3q*1D0 - ame**2*p2p4*p3q*1D0 -
     &        p1q*p2p4*p3q*1D0 - ame**2*p2p3*p4q*1D0 -
     &        p1q*p2p3*p4q*1D0 +
     &        kp3*(ame**2*p2q + p1q*(ame**2 + p2q) -
     &           ame**4*1D0 - ame**2*p1p2*1D0) -
     &        ame**2*kp1*1D0*(kp2 + p2p4 - p2p3*1D0)))/
     &    (kp4**2*p1q**2*(ampi**2 + kp3 + kp4 + p3p4)**2))
