        elmat = (CONJG(ffpiis)*ffpiintq*
     &    (p2p4*(ame**2*p1p2 + ame**2*p3q + p1q*p3q -
     &         ame**2*p1p3*1D0 - ame**2*p2q*1D0 -
     &         p1q*p2q*1D0 + ame**4*2D0 - ame**2*p1q*2D0) +
     &      p2p3*(ame**2*p1p4 + ame**2*p2q + p1q*p2q -
     &         ame**2*p1p2*1D0 - ame**2*p4q*1D0 -
     &         p1q*p4q*1D0 - ame**4*2D0 + ame**2*p1q*2D0)))/
     &  (p1q**2*(ampi**2 + p3p4)*(ampi**2 + kp3 + kp4 + p3p4)*
     &    (ampi**2 + p3p4 - p2p3*1D0 - p2p4*1D0))

