        elmat9 = (ame2*dme*5.D-1*
     &    (-(kp3**2*(ame2*kp4 + p1p4*(p2p4 - ame2*1D0))*
     &         2D0) - kp4*p1p3*2D0*
     &       (kp2*(p1p4 - ammu2*1D0) +
     &         kp4*(ame2 - p2p3*1D0) +
     &         2D0*(ammu2*p1p2 + p1p4*p2p3 + p1p3*p2p4 +
     &            ame2*(p3p4 + ammu2*2D0))) +
     &      kp3*2D0*(ame2*kp4**2 +
     &         kp4*(p1p4*(ame2 + p1p2 - p2p3*1D0) +
     &            ame2*(p2p4 - p2p3*1D0) -
     &            p1p3*1D0*(ame2 + p1p2 - p2p4*1D0)) +
     &         p1p4*(kp2*(p1p3 - ammu2*1D0) +
     &            2D0*(ammu2*p1p2 + p1p4*p2p3 + p1p3*p2p4 +
     &               ame2*(p3p4 + ammu2*2D0)))) +
     &      kp1*(kp3**2*(p1p4 - p2p4*1D0) +
     &         kp3*(kp4*p1p3 + kp4*p2p4 - kp4*p1p4*1D0 -
     &            kp4*p2p3*1D0 + ammu2*p1p2*2D0 +
     &            p1p3*p2p4*2D0 +
     &            p3p4*(ame2 - p1p4*1D0)*2D0 -
     &            kp2*1D0*(p3p4 + ammu2*3D0) +
     &            ame2*ammu2*4D0 - ammu2*p1p4*4D0 +
     &            p1p4*p2p3*4D0) +
     &         kp4*(kp4*p2p3 - kp4*p1p3*1D0 -
     &            ammu2*p1p2*2D0 - p1p4*p2p3*2D0 +
     &            p3p4*(kp2 - ame2*2D0 + p1p3*2D0) +
     &            ammu2*kp2*3D0 - ame2*ammu2*4D0 +
     &            ammu2*p1p3*4D0 - p1p3*p2p4*4D0)) -
     &      kp1**2*1D0*(kp3 - kp4*1D0)*(p3p4*3D0 + ammu2*5D0)
     &      ))/
     &  (kp1**2*kp3*kp4*(ame2 + p1p2)*(ammu2 + p3p4))


