        elmat10 = (ame2*dme*5.D-1*
     &    (2D0*(kp3**2*(ame2*kp4 +
     &            p2p4*(p1p4 - ame2*1D0)) +
     &         kp4*p2p3*(kp1*(p2p4 - ammu2*1D0) +
     &            kp4*(ame2 - p1p3*1D0) +
     &            2D0*(ammu2*p1p2 + p1p4*p2p3 + p1p3*p2p4 +
     &               ame2*(p3p4 + ammu2*2D0))) -
     &         kp3*1D0*(ame2*kp4**2 +
     &            kp4*(p1p4*(ame2 + p2p3) -
     &               p1p3*(ame2 + p2p4)*1D0 -
     &               (ame2 + p1p2)*1D0*(p2p3 - p2p4*1D0)) +
     &            p2p4*(kp1*(p2p3 - ammu2*1D0) +
     &               2D0*
     &                (ammu2*p1p2 + p1p4*p2p3 + p1p3*p2p4 +
     &                  ame2*(p3p4 + ammu2*2D0))))) +
     &      kp2*(kp3**2*(p1p4 - p2p4*1D0) +
     &         kp3*(kp4*(p1p3 - p1p4*1D0 - p2p3*1D0) -
     &            ammu2*p1p2*2D0 -
     &            2D0*(p1p4*p2p3 +
     &               ame2*(p3p4 + ammu2*2D0)) +
     &            kp1*(p3p4 + ammu2*3D0) +
     &            p2p4*(kp4 + p3p4*2D0 + ammu2*4D0 -
     &               p1p3*4D0)) +
     &         kp4*(ammu2*p1p2*2D0 +
     &            ame2*2D0*(p3p4 + ammu2*2D0) -
     &            p1p3*1D0*(kp4 - p2p4*2D0) -
     &            kp1*1D0*(p3p4 + ammu2*3D0) +
     &            p2p3*(kp4 - p3p4*2D0 - ammu2*4D0 +
     &               p1p4*4D0))) +
     &      kp2**2*(kp3 - kp4*1D0)*(p3p4*3D0 + ammu2*5D0)))/
     &  (kp2**2*kp3*kp4*(ame2 + p1p2)*(ammu2 + p3p4))

