        elmat23 = (B0ax34pp*5.D-1*(kp1**2*(p2p3 - p2p4*1D0) +
     &       kp1*(-((ame**2 + kp2)*1D0*
     &             (p1p3 + p2p4 - p1p4*1D0 - p2p3*1D0)) +
     &          kp4*(p1p2 + ame**2*2D0) -
     &          kp3*1D0*(p1p2 + ame**2*2D0)) +
     &       kp2*(ame**2*p1p4 + kp2*p1p4 + ame**2*p2p3 -
     &          ame**2*p1p3*1D0 - kp2*p1p3*1D0 -
     &          ame**2*p2p4*1D0 + kp3*(p1p2 + ame**2*2D0) -
     &          kp4*1D0*(p1p2 + ame**2*2D0))))/
     &   (kp1*kp2*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (C0appx34p0p*p3p4*2D0*
     &     (kp1**2*(p2p3 - p2p4*1D0) +
     &       kp1*(-((ame**2 + kp2)*1D0*
     &             (p1p3 + p2p4 - p1p4*1D0 - p2p3*1D0)) +
     &          kp4*(p1p2 + ame**2*2D0) -
     &          kp3*1D0*(p1p2 + ame**2*2D0)) +
     &       kp2*(ame**2*p1p4 + kp2*p1p4 + ame**2*p2p3 -
     &          ame**2*p1p3*1D0 - kp2*p1p3*1D0 -
     &          ame**2*p2p4*1D0 + kp3*(p1p2 + ame**2*2D0) -
     &          kp4*1D0*(p1p2 + ame**2*2D0))))/
     &   (kp1*kp2*(ame**2 + p1p2)*(ampi**2 + p3p4)) +
     &  (B0ap0p*(kp1**2*(p2p4 - p2p3*1D0) +
     &       kp2*(ame**2*p1p3 + kp2*p1p3 + ame**2*p2p4 -
     &          ame**2*p1p4*1D0 - kp2*p1p4*1D0 -
     &          ame**2*p2p3*1D0 + kp4*(p1p2 + ame**2*2D0) -
     &          kp3*1D0*(p1p2 + ame**2*2D0)) +
     &       kp1*((ame**2 + kp2)*
     &           (p1p3 + p2p4 - p1p4*1D0 - p2p3*1D0) +
     &          kp3*(p1p2 + ame**2*2D0) -
     &          kp4*1D0*(p1p2 + ame**2*2D0))))/
     &   (kp1*kp2*(ame**2 + p1p2)*(ampi**2 + p3p4))

