        elmat9 = (ammu**2*dmu*5.D-1*
     &    (kp1**2*(kp3*p2p4 + ammu**2*kp2*2D0 +
     &         p2p3*(-(kp3*1D0) + ammu**2*2D0 - p2p4*2D0)) +
     &      kp1*(-(ammu**2*kp2**2*2D0) +
     &         kp2*(kp3*p2p3 - kp3*p2p4*1D0 +
     &            ammu**2*p2p3*2D0 + ammu**2*p2p4*2D0 +
     &            p2p3*p3p4*2D0 +
     &            p1p4*(kp3 - (ammu**2 + p2p3)*2D0) -
     &            p1p3*1D0*
     &             (kp3 + (ammu**2 + p3p4 - p2p4*1D0)*2D0)) -
     &         p2p3*2D0*(kp4*(ame**2 - p1p3*1D0) +
     &            2D0*(ammu**2*p1p2 + p1p4*p2p3 + p1p3*p2p4 +
     &               ame**2*(p3p4 + ammu**2*2D0))) +
     &         kp3*(p1p3*p2p4*2D0 + ame**2*p3p4*2D0 +
     &            ammu**2*2D0*(p1p2 + ame**2*2D0) -
     &            p2p3*2D0*(p1p2 + ame**2*2D0 - p1p4*2D0) +
     &            kp4*(p1p2 + ame**2*3D0)) +
     &         kp3**2*(p1p2*3D0 + ame**2*5D0)) -
     &      kp2*1D0*(-(p1p3*2D0*
     &            (kp2*(p1p4 - ammu**2*1D0) +
     &              kp4*(ame**2 - p2p3*1D0) +
     &              2D0*(ammu**2*p1p2 + p1p4*p2p3 +
     &                 p1p3*p2p4 + ame**2*(p3p4 + ammu**2*2D0))
     &              )) +
     &         kp3*(ame**2*p3p4*2D0 +
     &            ammu**2*2D0*(p1p2 + ame**2*2D0) +
     &            p1p4*(kp2 + p2p3*2D0) +
     &            kp4*(p1p2 + ame**2*3D0) -
     &            p1p3*1D0*
     &             (kp2 + p1p2*2D0 + ame**2*4D0 - p2p4*4D0))
     &          + kp3**2*(p1p2*3D0 + ame**2*5D0))))/
     &  (kp1*kp2*kp3**2*(ame**2 + p1p2)*(ammu**2 + p3p4))



