        elmat = (CONJG(alphaT2)*alphaINTQ*
     &    (ame**4*kp3*kp4 + ame**6*kq + ame**6*p1p3 +
     &      ame**6*p1q + ame**4*kp3*p1q + ame**6*p2p4 +
     &      ame**4*kp3*p2p4 + ame**4*kp4*p2q +
     &      ame**4*kq*p2q + ame**4*p1p4*p2q +
     &      ame**2*kp3*p1p4*p2q + ame**4*p1q*p2q +
     &      ame**2*kp3*p1q*p2q + ame**4*p2q*p3p4 +
     &      ame**6*p3q + ame**4*p2q*p3q - ame**6*kp4*1D0 -
     &      ame**4*kp3*kq*1D0 - ame**6*p1p2*1D0 -
     &      ame**4*kp3*p1p2*1D0 - ame**6*p1p4*1D0 -
     &      ame**4*kp3*p1p4*1D0 - ame**6*p2p3*1D0 -
     &      ame**2*kp3*kp4*p2q*1D0 - ame**2*kp3*kq*p2q*1D0 -
     &      ame**4*p1p3*p2q*1D0 - ame**6*p3p4*1D0 -
     &      ame**6*p4q*1D0 - ame**4*kp3*p4q*1D0 -
     &      ame**4*p2q*p4q*1D0 - ame**2*kp3*p2q*p4q*1D0 +
     &      ame**2*kp1*(ame**2 - kp3*1D0)*
     &       (ame**2 - p2q*1D0) - ame**8*2D0 -
     &      ame**6*kp3*2D0 + ame**4*kq*p1p4*2D0 -
     &      ame**2*kp3*kq*p1p4*2D0 - ame**4*p1p4*p2p3*2D0 +
     &      ame**6*p2q*2D0 + ame**4*kp3*p2q*2D0 +
     &      ame**2*kq*p1p4*p2q*2D0 - kp3*kq*p1p4*p2q*2D0 +
     &      ame**4*p1p4*p3q*2D0 + ame**2*p1p4*p2q*p3q*2D0 -
     &      ame**2*kp2*1D0*(ame**2 - kp3*1D0)*
     &       (ame**2 + p1p4*2D0))*1.d0)/
     &  (kp3**2*p2q**2*(ame**2 + kp3 + kp4 + p3p4)*
     &    (p2p4 + p2q - ame**2*1D0 - p4q*1D0))
